#!/usr/bin/perl -w
=head1 NAME

 Auto configure service
 System conf

=cut

use strict;

BEGIN {
  our $libpath = '../';
  my $sql_type = 'mysql';
  use FindBin '$Bin';
  unshift(@INC,
    $Bin . '/' . $libpath . "Abills/$sql_type/",
    $Bin . '/' . $libpath . "Abills/modules/",
    $Bin . '/' . $libpath . '/lib/');

  eval {require Time::HiRes;};
  our $begin_time = 0;
  if (!$@) {
    Time::HiRes->import(qw(gettimeofday));
    $begin_time = Time::HiRes::gettimeofday();
  }
}

our (
  %conf,
  $db,
  $DATE,
  $TIME,
  $begin_time,
  @MODULES
);

my $VERSION = 4.10;
my $config_file = '/usr/abills/libexec/config.pl';

$conf{OS} = uc($^O);

$conf{WORK_DIR} = $Bin;
my $debug = 0;
use Abills::Base qw(startup_files parse_arguments mk_unique_value cmd);

# Default storage engine InnoDB,MyISAM
my $db_storage_engine = 'InnoDB';

my $argv = parse_arguments(\@ARGV);
if (!$argv->{OS}) {
  $argv->{OS} = $conf{OS};
}
else {
  $argv->{OS} = uc($argv->{OS});
  $conf{OS} = $argv->{OS};
}

my $default_mysql_root_passwd = '';
if ($argv->{MYSQL_ROOT_PASSWD}) {
  $default_mysql_root_passwd = $argv->{MYSQL_ROOT_PASSWD};
}

print "OS: $conf{OS}\n";

my $startup_files = startup_files();

if ($argv->{debug}) {
  $debug = int($argv->{debug});
  print "Debug mode: $debug\n";
}

if ($argv->{SYSTEM}) {
  system_conf();
}

if ($argv->{db_storage_engine}) {
  $db_storage_engine = $argv->{db_storage_engine};
}

if (!-f $config_file) {
  mk_config();
}

require $Bin . '/../libexec/config.pl';

$conf{DATE} = $DATE;
$conf{TIME} = $TIME;
$conf{WORK_DIR} = $Bin;

if ($argv->{CSUM}) {
  make_checksum();
  exit;
}
elsif ($argv->{help}) {
  help();
}
elsif (defined($argv->{INFO})) {
  my @programs = ();
  if ($argv->{INFO}) {
    @programs = split(/,/x, $argv->{INFO});
  }

  foreach my $program (@programs) {
    programs_info("$program");
  }
}
elsif ($argv->{PROGRAMS}) {
  my @programs = split(/,/x, $argv->{PROGRAMS});

  foreach my $program (@programs) {
    print "  PROGRAM: $program\n" if ($debug > 1);
    if (!-f $conf{WORK_DIR} . "/$program/install" && !defined($argv->{'-s'})) {
      print "Can't find program configuration '$conf{WORK_DIR}/$program/install'\n";
    }
    elsif ($debug < 6) {
      check_install("$program");
    }
  }
}
elsif ($argv->{INTERACT}) {
  interact_mode();
}
else {
  interact_mode();
}

#**********************************************************
=head3 mk_config()

  Arguments:

  Results:
    TRUE or FALSE

=cut
#**********************************************************
sub mk_config {

  print "System main configuration\n";
  my %mk_config = (
    'dbhost'     => 'localhost',
    'dbname'     => 'abills',
    'dbuser'     => 'abills',
    'dbpasswd'   => mk_unique_value(10),
    #'dbcharset'  => 'utf8',
    'ADMIN_MAIL' => '',
    'WEB_TITLE'  => ''
  );

  foreach my $k (sort keys %mk_config) {
    my $v = $mk_config{$k};
    print "$k [$v]: ";
    my $read = '';
    chop($read = <>);
    $read =~ s/^\s*//x;
    $read =~ s/\s*$//x;
    $read =~ s/\s*$//x;

    if ($read eq '') {
      #$mk_config{$VARIABLE} = $DEFAULT_VALUE{"$VARIABLE"};
    }
    else {
      $mk_config{$k} = $read;
    }
  }

  #Print result
  print "Configure.\n-----------------------------\n";
  while (my ($k, $v) = each %mk_config) {
    print "$k: $v\n";
  }

  my $config_text = read_file("$config_file" . '.default');

  while (my ($k, $v) = each %mk_config) {
    $config_text =~ s/\{$k\}\=\'\S{0,50}\'/\{$k\}\=\'$v\'/xg;
  }


  write_file($config_file, $config_text);
  print "Config file maked...\n";

  if (confirm_yn("Make ABillS mysql user account?", "y")) {
    mk_mysql(\%mk_config);
  }

  #Make periodic records in cron
  if (read_file('/etc/crontab') !~ /abills/xm && !confirm_yn("Make Cron records?", "n")) {
    my $crontab_content = "*/5  *  *  *  *  root   /usr/abills/libexec/billd -all\n" . "1    0  *  *  *  root   /usr/abills/libexec/periodic daily\n" . "1    1  *  *  *  root   /usr/abills/libexec/periodic monthly\n";
    write_file('/etc/crontab', $crontab_content, '>>');
  }

  if (!-d '/usr/abills/backup') {
    my $ret = cmd("mkdir /usr/abills/backup");
    $ret = cmd("chown $startup_files->{WEB_SERVER_USER} /usr/abills/backup /usr/abills/cgi-bin/ /usr/abills/Abills/templates/");
  }

  if (!confirm_yn("Continue configuration?", "y")) {
    exit;
  }

  return 1;
}

#**********************************************************
=head3 mk_mysql($mk_config)

  Arguments:
    $mk_config

  Results:
    TRUE or FALSE

=cut
#**********************************************************
sub mk_mysql {
  my ($mk_config) = @_;

  #Check mysql running
  my $proc_list = cmd("ps ax");
  print $proc_list if ($debug > 5);

  # Check /etc/my.cnf
  #if (!-f '/etc/my.cnf') {
  #  my $res = `cp mysql/my.cnf /etc/`;
  #}

  if ($proc_list !~ /mysqld/xm) {
    print "MySQL Not running. Start configure mysql\n";
    check_install("mysql");
  }

  my $mysql = '/usr/local/bin/mysql';
  if ($conf{OS} eq 'FREEBSD') {

  }
  #Other OS
  else {
    $mysql = '/usr/bin/mysql';
  }

  print "Check DB configuration\n";

  my $read;
  my $res;

  MYSQL_PROGRAM:
  if (!-f $mysql) {
    print "Can't find '$mysql', enter path:\n";
    chop($read = <STDIN>);
    $mysql = $read if ($read ne '');
    goto MYSQL_PROGRAM;
  }
  $mk_config->{dbcharset} = 'utf8';
  print "MySQL path: $mysql\n";

  my $mysql_root_user = 'root';
  my $mysql_root_passwd = $default_mysql_root_passwd || '';
  print "MySQL root user [$mysql_root_user]: ";
  chop($read = <STDIN>);
  $mysql_root_user = $read if ($read ne '');

  print "MySQL root password [$mysql_root_passwd]: ";
  chop($read = <STDIN>);
  $mysql_root_passwd = $read if ($read ne '');
  my $MYSQL_COLLATE = 'cp1251_general_ci';
  if ($mk_config->{dbcharset} eq 'utf8') {
    $MYSQL_COLLATE = 'utf8_general_ci';
  }

  my $mysql_version = cmd(qq/$mysql -N --default-character-set=$mk_config->{dbcharset} -u $mysql_root_user --password=$mysql_root_passwd -e "select version();"/);
  if ($mysql_version !~ /Unknown database/) {

    my $add_mysql_user = << "SQL";
    SET sql_mode=NO_ENGINE_SUBSTITUTION;
      CREATE DATABASE IF NOT EXISTS $mk_config->{dbname} DEFAULT CHARACTER SET $mk_config->{dbcharset} COLLATE $MYSQL_COLLATE;
      CREATE USER '$mk_config->{dbuser}'\@$mk_config->{dbhost}  IDENTIFIED BY '$mk_config->{dbpasswd}' ;
      GRANT ALL ON $mk_config->{dbname}.* TO '$mk_config->{dbuser}'\@localhost;
SQL
    # if inodb engine convert tables
    if (confirm_yn("Your DB is not configured for ABillS. Configure (will create mysql user, database and will import default sql dumps)?", "y")) {
      print "Make users\n";
      if ($debug > 0) {
        print $add_mysql_user;
      }

      $res = cmd(qq/$mysql --default-character-set=$mk_config->{dbcharset} -u $mysql_root_user --password='$mysql_root_passwd' -e "$add_mysql_user"/);
      if ($debug > 0) {
        print $res;
      }

      # my $mysql_version = `$mysql -N --default-character-set=$mk_config{dbcharset} -u $mysql_root_user --password='$mysql_root_passwd' -e "SELECT VERSION()"`;
      if ($mysql_version && $mysql_version =~ /^8/xm) {
        my $mysql_80_encodes = <<'SQL';
DELIMITER ||
CREATE
  DEFINER=root@localhost FUNCTION IF NOT EXISTS DECODE(ENCR BLOB, SECRETKEY VARCHAR(100)) RETURNS varchar(100) CHARSET utf8mb4
  DETERMINISTIC
  return cast(AES_DECRYPT(ENCR,sha2(SECRETKEY,256)) as char(200))||
DELIMITER ;

DELIMITER ||
CREATE
  DEFINER=root@localhost FUNCTION IF NOT EXISTS ENCODE(STR VARCHAR(200), SECRETKEY VARCHAR(100)) RETURNS blob
  DETERMINISTIC
  return AES_ENCRYPT(STR,sha2(SECRETKEY,256))||
DELIMITER ;
SQL

        if ($debug > 0) {
          print $mysql_80_encodes;
        }

        $res = cmd(qq/$mysql --default-character-set=$mk_config->{dbcharset} -u $mysql_root_user --password='$mysql_root_passwd' -D $mk_config->{dbname}   -e "$mysql_80_encodes"/);
      }

      print "Upload Main Dump and modules\n";
      $res = cmd(qq|$mysql --default-character-set=$mk_config->{dbcharset} -u $mysql_root_user --password='$mysql_root_passwd' -D $mk_config->{dbname} < ../db/abills.sql|);

      #Add connected modules sql dumps
      require $Bin . "/../libexec/config.pl";
      foreach my $module (@MODULES) {
        my $db_file = $Bin . "/../db/$module.sql";
        if (-f $db_file) {
          print "Loading MySQL dump for $module \n";
          $res = `$mysql --default-character-set=$mk_config->{dbcharset} -u $mysql_root_user --password='$mysql_root_passwd' -D $mk_config->{dbname} < $db_file`;
        }
      }
    }
    elsif (confirm_yn("Show MySQL queries, which will create user and database (you may want to run them manually)?", "y")) {
      print "----------------------------------------------------------\n" . "$add_mysql_user\n" . "----------------------------------------------------------\n";
    }
  }
  else {
    print $res;
  }

  return 1;
}

#**********************************************************
=head3 programs_info($program)

  Arguments:
    $program

  Results:
    TRUE or FALSE

=cut
#**********************************************************
sub programs_info {
  my ($program) = @_;
  print "Programs information: $program\n";

  my $install_file = $Bin . "/$program/install";

  my $content = read_file($install_file);
  my @files = split(/\n/x, $content);

  my %DEFAULT_VALUE = (WORK_DIR => $conf{WORK_DIR});
  my %DEFAULT_DESCRIBE = ();
  my %PARAMS_VALUES = ();
  my %PARAMS_HASH = ();

  # :DEFAULT:CLAMAV=1:Configure Clamav
  # :DEFAULT:CLAMAV=exec:hostname:Configure Clamav
  foreach my $file (@files) {
    if ($file =~ /^:DEFAULT:(.+)/xm) {
      my $value = $1;
      if ($value =~ /(\S+)=(.+|):(.+)/xm) {
        my $name = $1;
        $value = $2;
        my $describe = $3;

        #if ($value eq 'exec' && $describe =~ /(.+):(.+)/) {
        if ($value =~ /exec:(.+)/xm) {
          my $cmd = $1;
          #$describe = $2;
          $value = cmd($cmd);
          chomp($value);
        }

        print "DEFAULT: $name / $value / $describe \n" if ($debug > 2);
        $DEFAULT_DESCRIBE{"$name"} = $describe;
        $DEFAULT_VALUE{"$name"} = $value;
        $PARAMS_VALUES{"$name"} = $value;
        $PARAMS_HASH{"$name"} = $value;
      }
      next;
    }
    elsif ($file =~ /^:(\S{0,100}):(.+)\s+(>{1,2})\s+\[(\S+)\]\/(.+)/xm) {
      my $params = $1;

      #my $param_value = $2;
      my $param_name = '';
      my $param_value = '';
      my $value = $2;

      $value =~ s/\\n/\n/xg;

      if ($params) {
        my @params_arr = split(/,/x, $params);
        foreach my $param (@params_arr) {
          ($param_name, $param_value) = split(/=/x, $param, 2);
          $PARAMS_HASH{$param_name} = $param_value;
        }
      }
    }
  }

  while (my ($key, $value) = each %PARAMS_HASH) {
    print "$key ($value) \t";
    print " - " . $DEFAULT_DESCRIBE{$key} if ($DEFAULT_DESCRIBE{$key});
    print "\n";
  }

  return 1;
}

#**********************************************************
=head3 check_install($program)

  Arguments:
    $program
  Results:
    TRUE or FALSE

=cut
#**********************************************************
sub check_install {
  my ($program) = @_;

  my $install_file = $conf{WORK_DIR} . "/$program/install";

  my $content = read_file($install_file);
  my @files = split(/\n/x, $content);

  my %DEFAULT_VALUE = ();
  my %DEFAULT_DESCRIBE = ();
  $DEFAULT_VALUE{HOSTNAME} = cmd('hostname');
  chop($DEFAULT_VALUE{HOSTNAME});

  foreach my $file (@files) {
    my $config_body = '';
    my $type = '';
    my $folder = '';
    my $dest = '';

    #Reg expression
    print " > $file" if ($debug > 4);
    $file =~ s/[\r\n]+//xg;

    next if (!$file);
    next if ($file =~ /^\#/xm);

    # :DEFAULT:DEFAULT_VALUE_NAME=DEFAULT_VALUE_VALUE:DESCRIBE
    # Get default values
    if ($file =~ /^:DEFAULT:(.+)/xm) {
      my $value = $1;
      if ($value =~ /(\S+)=(.+|):(.{0,500})/xm) {
        my $name = $1;
        $value = $2;
        my $describe = $3;

        if ($value =~ /exec:(.+)/xm) {
          my $cmd = $1;
          #$describe = $2;
          $value = cmd($cmd);
          chomp($value);
        }
        print "DEFAULT: $name / $value / $describe \n" if ($debug > 2);
        $DEFAULT_DESCRIBE{"$name"} = $describe;
        $DEFAULT_VALUE{"$name"} = $value;
        if (!defined($argv->{"$name"})) {
          $argv->{"$name"} = $value;
        }
      }
      next;
    }
    #Execute some command
    #:PARAMS_NAME=PARAMS_VALUE:exec COMMAND
    elsif ($file =~ /^:(\S{0,100}):exec:(.+)/xm) {
      my $params = $1;
      my $value = $2;
      _exec_line({
        PARAM            => $params,
        VALUE            => $value,
        DEFAULT_VALUE    => \%DEFAULT_VALUE,
        DEFAULT_DESCRIBE => \%DEFAULT_DESCRIBE
      });
      next;
    }
    elsif ($file =~ /^:(\S{0,100}):(.+)\s+(>{1,2})\s+\[(\S+)\]\/(.+)/xm) {
      my $params = $1;
      my $value = $2;
      $type = $3;
      $folder = $4;
      $dest = $5;

      $value =~ s/\\n/\n/xg;
      #my %PARAMS_HASH         = ();
      #my %EXCLUDE_PARAMS_HASH = ();

      #Check params
      if ($params) {
        my $skip = 0;
        my @params_arr = split(/,/x, $params);
        foreach my $param (@params_arr) {
          my ($param_name2, $param_value2) = split(/=/x, $param, 2);
          if ($param_name2 =~ /^!(.+)/xm) {
            $param_name2 = $1;
            if (defined($argv->{$param_name2}) && $argv->{$param_name2} eq $param_value2) {
              print "$value\n Skip..\n" if ($debug > 2);
              $skip = 1;
              last;
            }
          }
          elsif (!defined($argv->{$param_name2}) || $argv->{$param_name2} ne $param_value2) {
            $skip = 1;
            last;
          }
          elsif ($param_name2 =~ /^!(\S+)/xm) {
            my $val = $1;
            if ($argv->{$val} && $argv->{$val} eq $param_value2) {
              $skip = 1;
              last;
            }
          }
        }
        next if ($skip);
      }

      if ($value =~ /^FILE=(\S+)/xm) {
        $config_body = read_file($conf{WORK_DIR} . "/$program/" . $1);
      }
      else {
        $config_body = "$value\n";
      }
    }
    elsif ($file =~ /^(\S+)\s+([>]{1,2})\s+\[(\S+)\]\/(.+)/xm) {
      my $config = $1;
      $type = $2;
      $folder = $3;
      $dest = $4;
      $config_body = read_file($conf{WORK_DIR} . "/$program/$config");
    }
    else {
      print "Unknown options:\n '$file'\n";
      next;
    }

    $config_body = _parse($config_body, \%DEFAULT_VALUE, \%DEFAULT_DESCRIBE);
    if ($folder) {
      $folder = _parse($folder, \%DEFAULT_VALUE, \%DEFAULT_DESCRIBE);
    }

    #Copy config
    if (!-d $folder) {
      if (!mkdir($folder)) {
        print "Can't Create '$folder' Error: $!\n";
        exit;
      }
      print "mkdir $folder\n" if ($debug == 2);
    }

    if ("$folder/$dest" =~ m/(\S+)\/([a-zA-Z0-9\-\.\_]+)$/xm) {
      my $desc_folder = $1;
      if (!-d $desc_folder) {
        if (!mkdir($desc_folder)) {
          print "Can't Create '$desc_folder' Error: $!\n";
          exit;
        }
        print "mkdir $desc_folder\n" if ($debug == 2);
      }
    }

    if ($debug == 3) {

    }
    else {
      #print "$type$folder/$dest";
      if ($type eq '>>') {
        if (!-d $folder) {
          print "Folder not exist '$folder'\n";
          next;
        }

        #Check fo existing record in file
        my $dest_body = read_file("$folder/$dest");

        $dest_body =~ s/\n|\r//xg;
        my $check_body = $config_body;
        $check_body =~ s/\n|\r//xg;
        $check_body =~ s/\$/\\\$/xg;

        if ($dest_body =~ m/$check_body/xsg) {
          print "File: $folder/$dest\n Skip. Parameters exists\n\n";
          if ($debug == 2) {
            print $config_body;
          }
          next;
        }
      }
      elsif (-e "$folder/$dest" && !defined($argv->{'-f'})) {
        if (!confirm_yn("File: $folder/$dest exists, overwrite?", "y")) {
          print "Skipped...\n";
          next;
        }
        elsif ($argv->{BACKUP}) {
          print "Make backup '$folder/$dest.bak'\n" if ($debug > 0);
          if (system("cp -R -pi $folder/$dest $folder/$dest.bak") == 0) {
            print "external cp command status was $?";
            exit;
          }
        }
      }

      write_file("$folder/$dest", $config_body, $type);
    }
  }

  return 1;
}

#********************************************************************
=head2 confirm_yn($message, $confirm)

  Arguments:
    $attr
      PARAM
      VALUE
      DEFAULT_VALUE
      DEFAULT_DESCRIBE

  Results:
    $self

=cut
#********************************************************************
sub _exec_line {
  my ($attr) = @_;

  my $params = $attr->{PARAM} || q{};
  my $value = $attr->{VALUE} || q{};
  my $DEFAULT_VALUE = $attr->{DEFAULT_VALUE};
  my $DEFAULT_DESCRIBE = $attr->{DEFAULT_DESCRIBE};

  if ($params ne q{}) {
    my $skip = 0;

    my @params_arr = split(/,/x, $params);
    foreach my $param (@params_arr) {
      my ($param_name2, $param_value2) = split(/=/x, $param, 2);
      if ($param_name2 =~ /^!(\S+)/xm) {
        my $val = $1;
        if ($argv->{$val} && $argv->{$val} eq $param_value2) {
          $skip = 1;
          last;
        }
      }
      elsif (!defined($argv->{$param_name2}) || $argv->{$param_name2} ne $param_value2) {
        $skip = 1;
        last;
      }
    }
    return 0 if ($skip);
  }

  my $config_body = "$value\n";

  print "EXECUTE: $config_body\n" if ($debug > 1);
  my $exec_cmd = '';
  my $exec_params_name = '';

  if ($config_body =~ /^(\S+)\=(.+)/xm) {
    $exec_params_name = $1;
    $exec_cmd = $2;
  }
  else {
    $exec_cmd = $config_body;
  }

  $exec_cmd = _parse($exec_cmd, $DEFAULT_VALUE, $DEFAULT_DESCRIBE);
  my $exec_file = '';

  if ($exec_cmd =~ /(\S+)/xm) {
    $exec_file = $1;
  }

  if ($exec_file =~ /\//xm && !-x $exec_file) {
    print "Error: File '$exec_file' not exist or not executable\n";
    return 0;
  }
  my $res = cmd($exec_cmd);
  print "RESULT: $res\n" if ($debug > 0);
  if ($exec_params_name ne '') {
    $DEFAULT_VALUE->{$exec_params_name} = $res;
  }

  return 1;
}

#********************************************************************
=head2 confirm_yn($message, $confirm)

  Arguments:
    $message
    $confirm
  Results:
    $self

=cut
#********************************************************************
sub confirm_yn {
  my ($message, $confirm) = @_;

  my $yes_ = '^(yes|YES|y|Y)$';
  my $no_ = '^(no|NO|n|N)$';
  my $read;

  if ($confirm && ($confirm =~ /$yes_/xm)) {
    $confirm = "y";
  }
  else {
    $confirm = "n";
  }
  print "$message (y/n) [$confirm]: ";
  chop($read = <STDIN>);
  $read =~ s/^\s*//x;
  $read =~ s/\s*$//x;
  return 1 if (!$read);

  if (($confirm eq "y" && $read =~ /$yes_/xmi)
    || ($confirm eq "n" && $read =~ /$no_/xmi)) {
    return 1;
  }

  if ($read !~ "$yes_" && $read !~ /$no_/xmi) {
    warn "Wrong value. Enter again!\a\n";
  }

  return 0;
}

#***********************************************
=head2 make_checksum() -  Make file checksum
=cut
#***********************************************
sub make_checksum {
  use DB_File;
  use DB_File;

  #$filename => "chacksum_type:checksum:filedate_time:permisions";
  my %hash = ();
  my @files = ();

  my $flags = "O_CREAT|O_RDWR";
  my $mode = '0700';
  my $DB_HASH;

  if ($argv->{CSUM_FILES}) {
    @files = split(/,/x, $argv->{CSUM_FILES});
  }
  elsif ($argv->{CSUM_DIRS}) {
    @files = read_file($argv->{CSUM_DIRS});
  }

  my $checksum_type = 'md5';
  my ($checksum, $filedate_time, $permisions);
  my $updated = "$DATE $TIME";
  my $checksum_file = $argv->{CHECKSUM_FILE} || 'checksum.db';
  print $checksum_file if ($debug > 0);

  my $db_ = tie %hash, 'DB_File', $checksum_file, $flags, $mode, $DB_HASH
    or print "Cannot open file '$checksum_file': $!\n";

  #Update checksum file
  if ($argv->{CSUM_UPDATE}) {
    foreach my $file (@files) {
      print $file . "\n" if ($debug > 0);
      my $value = "$checksum_type:$checksum:$filedate_time:$permisions:$updated";

      #my $status = $db->put($file, $value);
      if ($debug > 4) {next}
      $hash{$file} = $value;
    }
  }
  #compre with checksum file
  else {
    while (my ($k, $v) = each(%hash)) {
      print "$k, $v";
    }
  }

  undef $db_;
  untie %hash;

  return 1;
}

#**********************************************************
# Parse parameters
#**********************************************************
sub _parse {
  my ($parameter, $DEFAULT_VALUE, $DEFAULT_DESCRIBE) = @_;

  my %parse_value = (%$startup_files, %conf);

  while ($parameter =~ /%([A-Z\_0-9]+)%/xmg) {
    my $VARIABLE = $1;
    if (!$parse_value{$VARIABLE}) {
      print $DEFAULT_DESCRIBE->{"$VARIABLE"} . "\n" if ($DEFAULT_DESCRIBE->{"$VARIABLE"});
      print " $VARIABLE";
      print ' [' . $DEFAULT_VALUE->{"$VARIABLE"} . ']' if (defined($DEFAULT_VALUE->{"$VARIABLE"}));
      print ": ";
      my $read = '';
      chop($read = <STDIN>);
      $read =~ s/^\s*//x;
      $read =~ s/\s*$//x;

      #print "$VARIABLE  / $read\n";
      if ($read eq '' && defined($DEFAULT_VALUE->{"$VARIABLE"})) {
        $parse_value{$VARIABLE} = $DEFAULT_VALUE->{"$VARIABLE"};
      }
      else {
        $parse_value{$VARIABLE} = $read;
      }
    }
  }

  foreach my $key (sort keys %parse_value) {
    my $val = $parse_value{$key};
    $parameter =~ s/\%$key\%/$val/xg;
  }

  return $parameter;
}

#**********************************************************
=head3 read_file($filename)

  Arguments:
    $filename
    $attr
      DEBUG

  Results:
    $content

=cut
#**********************************************************
sub read_file {
  my ($filename, $attr) = @_;

  if ($attr->{DEBUG}) {
    print "Get content: $filename\n";
  }

  my $content = '';
  if (open(my $fh, '<', $filename)) {
    while (<$fh>) {
      $content .= $_;
    }
    close($fh);
  }
  else {
    print "Can't open file '$filename' $!";
    exit;
  }

  return $content;
}

#**********************************************************
=head3 write_file($filename, $content, $mode)

  Arguments:
    $filename
    $content
    $mode > | >>

  Results:
    $content

=cut
#**********************************************************
sub write_file {
  my ($filename, $content, $mode) = @_;

  if ($argv->{BACKUP}) {
    system("cp -R -pi $filename $filename.bak");
  }

  $mode = ($mode) ? $mode : '>';
  if (open(my $fh, $mode, "$filename")) {
    print $fh $content;
    close($fh);
  }
  else {
    print "Can't open file '$filename' $!";
    exit;
  }

  return $content;
}

#**********************************************************
=head2 interact_mode() Intercat secrvice installation

=cut
#**********************************************************
sub interact_mode {

  print "Interact ABillS Configuration ($Bin):\n";

  opendir(my $dh, $Bin) or print "Can't open dir '$conf{extern_acct_dir}' $!\n";
  my @contents = grep {!/^\.\.?$/xm} readdir $dh;
  closedir $dh;
  my @PROGRAMS = ();

  foreach my $dir (sort @contents) {
    if (-d "$Bin/$dir" && -f "$Bin/$dir/install") {
      push @PROGRAMS, $dir,;
    }
  }

  #my @installed = ();
  my $read = '';

  while (1) {
    if ($read && $read =~ /exit/xgi) {
      exit;
    }
    else {
      if ($read =~ /\d+/xm && $read > 0) {
        my $program = $PROGRAMS[ $read - 1 ];
        print "Configuration: $program\n";
        check_install("$program");
      }

      for (my $i = 1; $i <= $#PROGRAMS + 1; $i++) {
        my $program = $PROGRAMS[ $i - 1 ];
        print "$i. $program\n";
      }

      print "Select program or exit: ";
    }

    chop($read = <STDIN>);
  }

  return 1;
}

#**********************************************************
=head2 system_conf($attr) System conf

=cut
#**********************************************************
sub system_conf {

  if ($conf{OS} eq 'FREEBSD') {
    print "FreeBSD System configuration\n";
    my @rc_variables = (
      'usbd_enable,YES,',
      'sshd_enable,YES,',
      'inetd_enable,YES,',
      'gateway_enable,YES,',
      'local_startup,/usr/local/etc/rc.d,',

      'hostname,abills-flash-nas,',
      'defaultrouter,10.0.0.1,',

      #   'ipcad_enable,YES,',
      #   'flow_capture_enable,YES,',
      #   'flow_capture_datadir,/usr/abills/var/log/ipn/,',
      #   'flow_capture_port,9996,',
      #   'flow_capture_flags,-S 5 -n 287 -N 0 -d 5,',

      #firewall_enable="YES"
      'firewall_type,/etc/fw.conf,',
      'natd_enable,YES,',
      'natd_interface,lnc0,',

      #   'dhcpd_enable,YES,',

      #PPPoE
      #   'pppoed_enable,YES,',
      #   'pppoed_flags,-d -l pppoe-in',
      #   'pppoed_interface,em1,',

      'ntpdate_enable,YES,',
      'ntpdate_flags,europe.pool.ntp.org',
      'named_enable,YES,',

    );

    #Makwe interface config
    my $res = cmd('ifconfig');
    my @arr = split(/\n/x, $res);

    foreach my $line (@arr) {
      #print $line."\n";
      if ($line =~ /^(\S+):/xm) {
        my $iface = "$1";
        if ($iface ne 'lo0') {
          @rc_variables = ("ifconfig_$iface,inet xxx.xxx.xxx.xxx netmask xxx.xxx.xxx.xxx,Interface configuration", @rc_variables);
        }
      }
    }

    #'ifconfig_lnc0,inet 10.0.0.10 netmask 255.255.255.0,',

    my @rc_result = ();
    my $read;
    foreach my $line (@rc_variables) {
      my ($name, $default, $describe) = split(/,/x, $line, 3);

      print "$describe\n$name [$default]: ";

      chop($read = <>);
      if ($read !~ /^n$|^no$/xgi) {
        if ($read eq '') {
          $read = $default;
        }
        push @rc_result, "$name,$read";
      }
    }

    #Show result
    my $content = '';
    foreach my $line (@rc_result) {
      my ($name, $val) = split(/,/x, $line);
      $content .= "$name=\"$val\"\n";
    }

    if (confirm_yn("Make /etc/rc.conf?", 'y')) {
      write_file('/etc/rc.conf', $content, '>');
      print "Done\n";
    }
  }

  return 1;
}

#**********************************************************
#
#**********************************************************
sub other_options {

  #ntpdate_flags="europe.pool.ntp.org"
  #ntpdate_enable="YES"

  # named_enable="YES"
}


#**********************************************************
#
#**********************************************************
sub help {

  print <<"[END]";
Auto configuration script Version: $VERSION
 ./autoconf [parameters]
  PROGRAMS=[PROGRAMS,...] - Program names (postfix,freeradius,exppp)
  INFO=[PROGRAMS,...]     - Program information (postfix,freeradius,exppp)
  SYSTEM                  - System config
  -f                      - Force mode. Rewrite exists files withot prompt
  -s                      - skip exit for unknown install programs
  OS=                     - Operation system
  PARAMS=                 - Extended parameters
    FREEBSD               - OS FreeBSD make startup config
  CHANGE_PATH             - Change path for instalation files.

  FILES                   - Configure only selected files

  CSUM                    - Compare checksum
  CSUM_UPDATE=[file,...]  - Update checksum
  CSUM_FILE=[file]        - Checksum summary file. Default checksum.db
  CSUM_DIR=[dir,...]      - Make checksum for all dir files
  CSUM_FILES=[file,...]   - Make checksum for files
  ATOCONF_CHECKSUM        - Make checksum for autoconfigure files

  debug                   - Debug level
                            1 short debug
                            2 full debug
                            3 emulate mode
  BACKUP                  - Backup old configuration files (add .bak extention)
  db_storage_engine=      - Database Storage engine (InnoDB,MyISAM). Default: $db_storage_engine
  INFORMATION:
   OS: $conf{OS}
[END]

  return 1;
}

1;
