#!/usr/bin/perl
=head1 NAME

 PaySys Console
 Console interface for payments and fees import

=cut

use strict;
use warnings;

our (
  $begin_time,
  %FORM,
  $DATE,
  $TIME,
  $CHARSET,
  @MODULES,
  @_COLORS,
  %conf,
  %lang
);

BEGIN {
  use FindBin '$Bin';
  my $libpath = $Bin . '/../../../';
  our $sql_type = 'mysql';

  #unshift(@INC, $libpath . "Abills/$sql_type/");
  unshift(@INC, $libpath);
  unshift(@INC, $libpath . 'libexec/');
  unshift(@INC, $libpath . 'lib/');
  unshift(@INC, $libpath . 'Abills/');

  unshift(@INC, '/usr/abills/');
  unshift(@INC, '/usr/abills/Abills/');
  unshift(@INC, "/usr/abills/Abills/$sql_type/");
  unshift(@INC, $libpath . "/Abills/modules/");
  unshift(@INC, '../../' . "$sql_type/");

  eval { require Time::HiRes; };
  if (!$@) {
    Time::HiRes->import(qw(gettimeofday));
    $begin_time = Time::HiRes::gettimeofday();
  }
  else {
    $begin_time = 0;
  }
}

require $Bin . '/../../../libexec/config.pl';


use Abills::Templates;
use Abills::Base qw(convert decode_base64 sendmail days_in_month parse_arguments in_array load_pmodule cmd date_format);
use Abills::SQL;
use Abills::HTML;
use Users;
use Paysys;
use Finance;
use Admins;
use Customers;
use Paysys::Init;
use Paysys::Statements;

our $html = Abills::HTML->new();
our $db   = Abills::SQL->connect($conf{dbtype},
  $conf{dbhost},
  $conf{dbname},
  $conf{dbuser},
  $conf{dbpasswd},
  { %conf, CHARSET => ($conf{dbcharset}) ? $conf{dbcharset} : undef });

#Operation status
our $admin  = Admins->new($db, \%conf);
$admin->info($conf{SYSTEM_ADMIN_ID}, { IP => '127.0.0.1' });
our Payments $Payments  = Finance->payments($db, $admin, \%conf);
my $Fees      = Finance->fees($db, $admin, \%conf);
our $Paysys   = Paysys->new($db, $admin, \%conf);
my $Users     = Users->new($db, $admin, \%conf);
my $Paysys_Statements = Paysys::Statements->new($db, $admin, \%conf);

#my $status   = '';
my $debug     = 0;
my $error_str = '';

do "Abills/Misc.pm";

my $argv = parse_arguments(\@ARGV);

if ($#ARGV < 0 || defined($argv->{help}) || defined($argv->{'-h'}) ) {
  help();
  exit;
}

if ($argv->{DEBUG}) {
  $debug = $argv->{DEBUG};
  print "DEBUG: $debug\n";
}

my DBI $db_ = $db->{db};

do "language/$conf{default_language}.pl";
do 'Paysys/lng_'.$conf{default_language}.'.pl';

$DATE = $argv->{DATE} if ($argv->{DATE});

if ($argv->{PLUGIN}) {
  if (-f ($Bin . '/plugins/' . $argv->{PLUGIN})) {
    require $Bin . '/plugins/' . $argv->{PLUGIN};
  }
  else {
    print "Plugin not found: $argv->{PLUGIN}\n";
  }
}
elsif ($argv->{TYPE}) {
  my $operation_type = $argv->{TYPE};

  if ($argv->{EMAIL_CHECK}) {
    paysys_import_pop3();
  }
  elsif ($argv->{FTP_CHECK}) {
    paysys_import_ftp();
  }
  elsif ($operation_type eq 'PAYMENTS' || $operation_type eq 'CANCEL_PAYMENTS' || $operation_type eq 'AUTO') {
    paysys_import_payments_cons();
  }
  elsif ($operation_type eq 'FEES') {
    paysys_import_fees_cons();
  }
}

#**********************************************************
=head2 paysys_import_form_cons($attr) - Import fees from_file

=cut
#**********************************************************
sub paysys_import_form_cons {
  my ($attr) = @_;

  my @import_types = ();
  if ($attr->{IMPORT_RULES}) {
    @import_types = split(',', $attr->{IMPORT_RULES});
  }

  #my $table;
  #Default import extration
  my $import_expr = ($attr->{IMPORT_EXPR}) ? $attr->{IMPORT_EXPR} : '(\d+)\t(.+)\t(\d+)\t(\S+)\t([0-9.,]+)\t(\d{2}-\d{2}-\d{4})\t(.+)\t(.+):ID, FIO, PHONE, CONTRACT_ID, SUM, DATE, ADDRESS, DESCRIBE';

  #Default Binding field
  my $BINDING_FIELD = ($attr->{BINDING_FIELDS}) ? $attr->{BINDING_FIELDS} : 'CONTRACT_ID';

  if (defined($attr->{IMPORT_RULE})) {
    $import_expr       = $conf{ 'PAYSYS_IMPORT_EXPRATION_' . $attr->{IMPORT_RULE} };
    $BINDING_FIELD     = $conf{ 'PAYSYS_IMPORT_BINDING_' . $attr->{IMPORT_RULE} } if ($conf{ 'PAYSYS_IMPORT_BINDING_' . $attr->{IMPORT_RULE} });
    $FORM{IMPORT_TYPE} = $attr->{IMPORT_RULE};
  }

  my ($DATA_ARR, $BINDING_IDS);
  my %binding_hash      = ();
  my $total_count       = 0;
  my $total_sum         = 0;
  my $total_added_count = 0;
  my $total_added_sum   = 0;
  if (!$argv->{FILE} && !$attr->{CONTENT}) {
    print "Select input file !!!\n";
    exit;
  }

  my $content  = '';
  my $filename = $argv->{FILE} || '';

  if ($attr->{CONTENT}) {
    $content = $attr->{CONTENT};
  }
  else {
    open(my $fh, '<', "$filename") || die "Can't open file '$filename' $!\n";
    while (<$fh>) {
      $content .= $_;
    }
    close($fh);
  }

  #TODO: rewrite to date_format after task #6123
  ($DATA_ARR, $BINDING_IDS) = $Paysys_Statements->paysys_import_parse(
    $content,
    $import_expr,
    $BINDING_FIELD,
    { SKIP_ROWS => $argv->{SKIP_ROWS} }
  );

  #Make users binding hash
  my %binds_hash = map { $_ => 1} @$BINDING_IDS;
  my $ids   = join(';', keys %binds_hash);

  my $accounts_list;
  if(in_array($BINDING_FIELD, [ 'BANK_ACCOUNT', 'TAX_NUMBER' ])) {
    print "Company ids: $BINDING_FIELD // $ids !!!\n" if($debug > 4);
    my $Customer = Customers->new($db, $admin, \%conf);
    my $Company  = $Customer->company();
    $accounts_list = $Company->list({
      FIO            => '_SHOW',
      LOGIN          => '_SHOW',
      BILL_ID        => '_SHOW',
      UID            => '_SHOW',
      $BINDING_FIELD => $ids,
      PAGE_ROWS      => 1000000,
      COLS_NAME      => 1,
      COMPANY_ADMIN  => '_SHOW'
    });
  }
  else {
    $Users->{debug} = 1 if ($debug > 7);
    $accounts_list = $Users->list({
      FIO            => '_SHOW',
      LOGIN          => '_SHOW',
      $BINDING_FIELD => $ids,
      PAGE_ROWS      => 1000000,
      COLS_NAME      => 1
    });
  }

  my $binding_field_id = lc($BINDING_FIELD);

  foreach my $line (@$accounts_list) {
  	if (! defined($line->{$binding_field_id})) {
  		print "Not defined bind field '$binding_field_id'\n";
  		exit;
  	}

    if (! defined($line->{uid})) {
      print "Company ID '$line->{id}' has no users. Skipping.\n";
      next;
    }

  	$line->{login} = (! $line->{login}) ? $line->{id} : $line->{login};
    $binding_hash{ lc($line->{$binding_field_id}) } = "$line->{uid}:$line->{login}:" . (($line->{fio}) ? $line->{fio} : '');
  }

  $Payments->{debug} = 1 if ($debug > 4);

  my $error = 0;
  for (my $i = 0 ; $i <= $#{$DATA_ARR} ; $i++) {
    my $ID = $DATA_ARR->[$i]->{PAYSYS_EXT_ID} || $i;
    $DATA_ARR->[$i]->{DATE} = $DATE if (!$DATA_ARR->[$i]->{DATE});

    if ($binding_hash{ lc($DATA_ARR->[$i]->{$BINDING_FIELD}) }) {
      my ($uid, $login, $fio) = split(':', $binding_hash{ lc($DATA_ARR->[$i]->{$BINDING_FIELD}) });

      if($debug > 2) {
        print "UID: $uid LOGIN: $login FIO: $fio\n";
      }

      next if ($DATA_ARR->[$i]->{SUM} == 0);
      $error     = 0;
      $error_str = '';
      my $user           = $Users->info($uid);
      # delete param for cross modules
      delete $user->{PAYMENTS_ADDED};
      
      my $describe       = $DATA_ARR->[$i]->{DESCRIBE} || '';
      my $inner_describe = $DATA_ARR->[$i]->{INNER_DESCRIBE} || '';
      if ($describe ne '' && $argv->{DECODE}) {
        $describe = convert($describe, { $argv->{DECODE} => 1 });
      }

      if ($inner_describe ne '' && $argv->{DECODE}) {
        $inner_describe = convert($inner_describe, { $argv->{DECODE} => 1 });
      }

      $db_->{AutoCommit}=0;
      $db->{TRANSACTION}=1;

      my $operation_type = '';

      if($argv->{TYPE} eq 'AUTO') {
        if($DATA_ARR->[$i]->{SUM} < 0) {
          $operation_type= 'FEES';
          $DATA_ARR->[$i]->{SUM} = abs($DATA_ARR->[$i]->{SUM});
        }
        else {
          $operation_type = 'PAYMENTS';
        }
      }
      else {
        $operation_type = $argv->{TYPE};
      }

      if ($operation_type eq 'PAYMENTS') {
        my $ext_id = '';
        if ($debug < 6) {
          $DATA_ARR->[$i]->{DATE} = date_format($DATA_ARR->[$i]->{DATE}, '%Y-%m-%d');

          my $method = $DATA_ARR->[$i]->{PAYMENT_METHOD} || $argv->{METHOD} || 2;
          $ext_id = $DATA_ARR->[$i]->{EXT_ID} || "$DATA_ARR->[$i]->{DATE}_$FORM{IMPORT_TYPE}.$ID";

          if (! $DATA_ARR->[$i]->{TIME}) {
            $DATA_ARR->[$i]->{TIME}=$TIME;
          }

          $Payments->add($user, {
            SUM            => $DATA_ARR->[$i]->{SUM},
            DESCRIBE       => $describe,
            METHOD         => $method,
            DATE           => "$DATA_ARR->[$i]->{DATE} $DATA_ARR->[$i]->{TIME}",
            EXT_ID         => $ext_id,
            CHECK_EXT_ID   => $ext_id,
            INNER_DESCRIBE => $inner_describe,
            CURRENCY       => $conf{SYSTEM_CURRENCY} || 0
          });
        }

        if ($Payments->{errno} && $Payments->{errno} == 7) {
          $error_str .= "ERROR: EXIST EXT_ID: $ext_id\n";
          if ($debug > 2) {
            $error_str .= "ID: $Payments->{ID} DATE: $Payments->{DATE} SUM: $Payments->{SUM} UID: $Payments->{UID}\n";
          }
          $error     = 1;
        }
        else {
          if (! $argv->{SKIP_CROSSMODULES_CALLS}) {
            cross_modules('payments_maked', {
              USER_INFO    => $user,
              QUITE        => 1,
              SUM          => $DATA_ARR->[$i]->{SUM},
              PAYMENT_ID   => $Payments->{PAYMENT_ID},
              SKIP_MODULES => 'Paysys,Sqlcmd'
            });
          }
        }
      }
      elsif ($operation_type eq 'FEES') {
        if ($debug < 5) {
          $Fees->take(
            $user,
            $DATA_ARR->[$i]->{SUM},
            {
              DESCRIBE       => $describe,
              INNER_DESRIBE  => $DATA_ARR->[$i]->{EXT_ID},
              DATE           => $DATA_ARR->[$i]->{DATE} || undef,
              INNER_DESCRIBE => $inner_describe,
              METHOD         => $DATA_ARR->[$i]->{PAYMENT_METHOD} || $argv->{METHOD},
            }
          );
        }

        if ($Fees->{errno} && $Fees->{errno} == 7) {
          $error_str .= "ERROR: EXIST: EXT_ID: $DATA_ARR->[$i]->{DATE}.$ID\n";
          $error     = 1;
        }
      }
      elsif ($operation_type eq 'CANCEL_PAYMENTS') {
        my @payments_arr = ();
        for (my $num = 0 ; $num <= $#{$DATA_ARR} ; $num++) {
          #my $ID = $DATA_ARR->[$num]->{PAYSYS_EXT_ID} || $i;
          if ($DATA_ARR->[$num]->{EXT_ID}) {
            if ($argv->{PAYSYS_EXT_ID}) {
              push @payments_arr, "$DATA_ARR->[$num]->{DATE}*$DATA_ARR->[$i]->{EXT_ID}";
            }
            else {
              push @payments_arr, $DATA_ARR->[$i]->{EXT_ID};
            }
          }
        }

        if ($#payments_arr == -1) {
          print "Select ext ID for cancel payments\n";
          return 0;
        }

        my $payment_list = $Payments->list({
          EXT_ID    => join(';', @payments_arr),
          PAGE_ROWS => 10000000,
          COLS_NAME => 1
        });

        foreach my $p (@$payment_list) {
          $Payments->del({ UID => $p->{uid} }, $p->{id});
          print "ID: $p->{id} SUM: $p->{uid}\n" if ($debug > 1);
        }
      }

      if (!$error) {
        if (! $db_->{AutoCommit}) {
          $db_->commit();
          $db_->{AutoCommit}=1;
        }

        $total_added_count++;
        $total_added_sum += $DATA_ARR->[$i]->{SUM};
      }
      else {
        $db_->rollback() if(! $db_->{AutoCommit});
      }
    }
    else {
      $error_str = "ERROR: NOT_EXIST BIND_FIELD: $BINDING_FIELD - $DATA_ARR->[$i]->{$BINDING_FIELD} DATE: $DATA_ARR->[$i]->{DATE} SUM: $DATA_ARR->[$i]->{SUM}\n ";
    }

    print $error_str if ($error_str ne '');

    $total_count++;
    $total_sum += $DATA_ARR->[$i]->{SUM};
  }

  if ($debug > 0) {
    print "
  TOTAL: $total_count SUM: $total_sum
  ADDED: $total_added_count SUM: $total_added_sum\n";
  }

  if ($error_str) {
  	print "Error: $error_str\n";
  }

  return ($error) ? 0 : 1;
}

#**********************************************************
=head2 paysys_import_fees_cons($attr) Import fees from_file

=cut
#**********************************************************
sub paysys_import_fees_cons {
  return paysys_import_form_cons({
    TYPE           => 'FEES',
    BINDING_FIELDS => $conf{PAYSYS_FEES_BINDING},
    IMPORT_EXPR    => $conf{PAYSYS_FEES_IMPORT},
    IMPORT_RULES   => 'FEES'
  });
}

#**********************************************************
=head2 paysys_import_payments_cons($attr) Import fees from_file

=cut
#**********************************************************
sub paysys_import_payments_cons {
  my @files = ();
  my $filename = $argv->{FILE} || '';
  my $dir   = '';

  if ($filename =~ s/\*/\.\+/xg) {
    $dir = dirname($filename);
    $filename =~ s/$dir\///x;
    opendir my $dh, $dir or die "Can't open dir '$dir' $!\n";
      @files = grep /^$filename$/x, readdir $dh;
    closedir $dh;
  }
  else {
    push @files, $filename;
  }

  foreach my $filename_ (@files) {
    $filename_ = "$dir/$filename_" if ($dir);
    my $content = '';
    open(my $fh, '<', $filename_) || die "Can't open file '$filename_' $!\n";
      while (<$fh>) {
        $content .= $_;
      }
    close($fh);

    paysys_import_form_cons({
      TYPE         => $argv->{TYPE},
      IMPORT_RULE  => $argv->{IMPORT_RULE},
      IMPORT_RULES => $conf{PAYSYS_IMPORT_RULES},
      CONTENT      => $content
    });

    if ($debug < 5) {
      if ($argv->{BACKUP_FILES} && -d $argv->{BACKUP_FILES}) {
        cmd("cp $filename_ $argv->{BACKUP_FILES}");
      }
      #unlink $filename;
    }
  }

  return 1;
}

#**********************************************************
=head2 paysys_import_pop3() - import data from mail with POP3

=cut
#**********************************************************
sub paysys_import_pop3 {
  print "POP3 check\n" if ($debug > 2);

  load_pmodule('Net::POP3');

  # Constructors
  my @mailboxes = split(';', $conf{PAYSYS_EMAIL_CHECK});

  if ($argv->{EMAIL_CHECK} ne '') {
    $argv->{EMAIL_CHECK}--;
    if (!$mailboxes[ $argv->{EMAIL_CHECK} ]) {
      print "Not defined mail box '$argv->{EMAIL_CHECK}'\n";
      exit;
    }
    else {
      @mailboxes = ($mailboxes[ $argv->{EMAIL_CHECK} ]);
    }
  }

  foreach my $mailbox (@mailboxes) {
    my ($host, $username, $password) = split(':', $mailbox, 3);

    my $pop = Net::POP3->new($host, Timeout => 60, SSL => $argv->{SSL} || 0);
    if (!$pop) {
      print "POP3 Error: Can't connect '$host' $!\n";
      exit;
    }

    if ($pop->login($username, $password)) {
      my $msgnums = $pop->list;       # hashref of msgnum => size
      my $total   = keys %$msgnums;
      print "Total: $total\n\n" if ($debug > 2);

      foreach my $msgnum (keys %$msgnums) {
        my $content = '';
        #my $uidl    = $pop->uidl($msgnum);
        my $msg     = $pop->get($msgnum);
        my $full_message = join('', @$msg);
        my ($header, $message) = split(/\r?\n\r?\n/x, $full_message, 2);

        # Parse header
        my @lines      = split(/\r?\n/x, $header);
        my $boundary   = '';
        my $date       = '';
        my $subject    = '';
        my $message_id = '';

        foreach my $line (@lines) {
          if ($line =~ /boundary="(.+)"/xi) {
            $boundary = $1;
          }
          elsif ($line =~ /Subject: (.+)/x) {
            $subject = $1;
          }
          elsif ($line =~ /Date: (.+)/x) {
            $date = $1;
          }
          elsif ($line =~ /Message-ID: (.+)/x) {
            $message_id = $1;
          }
        }

        my @parts = ();
        if ($boundary ne '') {
          @parts = split(/--$boundary/x, $message);
        }

        my $filename = '';
        if ($#parts > -1) {
          foreach my $part (@parts) {
            my $encoding = '';

            my ($part_header, $part_body) = split(/\r?\n\r?\n/x, $part, 2);
            @lines = ();
            @lines = split(/\r?\n/x, $part_header) if ($part_header);
            foreach my $line (@lines) {
              if ($line =~ /filename="(.+)"/xi) {
                $filename = $1;
              }
              elsif ($line =~ /name="=(.+)="/x){
                my $coded_filename = $1;
                ($coded_filename) = $coded_filename =~ /\?UTF-8\?B\?(.+)?/x;

                $filename = decode_base64($coded_filename);
              }
              elsif ($line =~ /Content-Transfer-Encoding: (.+)/xi) {
                $encoding = $1;
              }
            }

            if ($encoding eq 'base64') {
              $content .= "\n" . decode_base64($part_body);
            }
          }
        }
        else {
          $content .= $message;
        }

        if ($argv->{DECODE}) {
          $content = convert($content, { $argv->{DECODE} => 1 });
        }

        my $check = paysys_import_form_cons({
          TYPE         => $argv->{TYPE},
          IMPORT_RULE  => $argv->{IMPORT_RULE},
          IMPORT_RULES => $conf{PAYSYS_IMPORT_RULES},
          CONTENT      => $content,
        });

        if ($check) {
          $pop->delete($msgnum);
          print "Delete\n" if ($debug == 1);
        }
        else {
          $message = << "MSG";
   Date:  $date
   Subject: $subject
   Message id: $message_id

   $content

   Error: $error_str
MSG

          sendmail("$conf{ADMIN_MAIL}", "$conf{ADMIN_MAIL}", "POP3 Import Error", "$message", "$conf{MAIL_CHARSET}", "2 (High)");
        }
      }

      $pop->quit();
    }
    else {
      print "POP3 Error: Wrong login or password $!\n";
    }
  }
  #return $content;
}

#**********************************************************
=head2 paysys_import_ftp($attr) - import data from ftp

  Arguments:
    $attr

  Return:
    $content

=cut
#**********************************************************
sub paysys_import_ftp {
  my ($attr) = @_;

  print "FTP check\n" if ($debug > 2);
  my @hosts = ();
  # Constructors

  if (!$conf{PAYSYS_SFTP_CHECK} && !$conf{PAYSYS_FTP_CHECK}) {
    print "Do not have settings for import!Please, check config.pl and documentation.\n";
    exit;
  }

  if ($conf{PAYSYS_SFTP_CHECK}) {
    load_pmodule('Net::FTPSSL');
    @hosts = split(';', $conf{PAYSYS_SFTP_CHECK});
  }
  else {
    load_pmodule('Net::FTP');
    @hosts = split(';', $conf{PAYSYS_FTP_CHECK});
  }

  if ($argv->{FTP_CHECK} && $argv->{FTP_CHECK} ne '') {
    $argv->{FTP_CHECK}--;
    if (!$hosts[ $argv->{FTP_CHECK} ]) {
      print "Not defined FTP '$argv->{FTP_CHECK}'\n";
      exit;
    }
    else {
      @hosts = ($hosts[ $argv->{FTP_CHECK} ]);
    }
  }

  foreach my $host_params (@hosts) {
    my ($host, $username, $password, $dir, $files, $passive_mode) = split(':', $host_params, 6);
    my $ftp = qq{};
    if ($conf{PAYSYS_SFTP_CHECK}) {
      $ftp = Net::FTPSSL->new("$host", useSSL => 0, Debug => 0, Port => 21, SSL_Client_Certificate => {
        SSL_version   => 'TLSv1',
      }) or die "Cannot connect to '$host': $@";
    }
    else {
      $ftp = Net::FTP->new("$host", Debug => 0, Passive => $passive_mode || 0)
        or die "Cannot connect to '$username\@$host': $@";
    }

    if ($ftp->login("$username", "$password")) {
      $dir = $attr->{FTP_DIR} if ($attr->{FTP_DIR});
      if ($dir) {
        $ftp->cwd("$dir")
        or die "Cannot change working directory '$dir' ", $ftp->message;
      }

      if ($attr->{UPLOAD}) {
        $ftp->put("$attr->{UPLOAD}")
        or die "Ftp get failed '$attr->{UPLOAD}' ", $ftp->message;
        print "Upload: $attr->{UPLOAD}\n" if ($debug > 1);
        next;
      }

      my $files_arr = $ftp->ls("$files");
      foreach my $filename (@$files_arr) {
        my $content = '';
        $ftp->get("$filename")
        or die "Ftp get failed '$filename' ", $ftp->message;
        print $filename. "\n" if ($debug > 2);

        my ($local_filename) = $filename =~ /\/?([a-zA-Z0-9\.\-\_\?]+)$/x;
        open(my $fh,'<', "$local_filename") || die "Can't open file '$filename' $!\n";
        while (<$fh>) {
          $content .= $_;
        }
        close($fh);

        if ($argv->{DECODE}) {
          $content = convert($content, { $argv->{DECODE} => 1 });
        }

        my $import_result = paysys_import_form_cons({
          TYPE         => $argv->{TYPE},
          IMPORT_RULE  => $argv->{IMPORT_RULE},
          IMPORT_RULES => $conf{PAYSYS_IMPORT_RULES},
          CONTENT      => $content
        });

        if ($import_result){
          if ($argv->{BACKUP_FILES} && -d $argv->{BACKUP_FILES}) {
            cmd("cp $local_filename $argv->{BACKUP_FILES}");
          }
          unlink $local_filename;

          $ftp->delete("$filename") or die "Ftp del failed '$filename'\n", $ftp->message;

          print "Delete LOCAL:$local_filename 'FTP:$filename'\n" if ($debug > 0);
        }
        else {
          my $message = << "MSG";
   ERROR paysys_cons:
   Filename: $filename

   $content

   Error: $error_str
MSG

          sendmail("$conf{ADMIN_MAIL}", "$conf{ADMIN_MAIL}", "FTP Import Error", "$message", "$conf{MAIL_CHARSET}", "2 (High)");
        }
      }
    }
    else {
      print "FTP Error: Wrong login or password $!\n";
    }
  }

  return '';
}

#**********************************************************
# Main iport  parser
#**********************************************************
# sub paysys_import {
#
# }

#**********************************************************
=head2 help() - show manual

=cut
#**********************************************************
sub help {

  my @import_rules_arr = ();
  if ($conf{PAYSYS_IMPORT_RULES}) {
    @import_rules_arr = split(',', $conf{PAYSYS_IMPORT_RULES});
  }

  my $import_rules = '';
  for (my $i = 0 ; $i <= $#import_rules_arr ; $i++) {
    $import_rules .= "      $i - $import_rules_arr[$i]\n";
  }

  print << "[END]"
Paysys console interface:

  TYPE=[PAYMENTS|CANCEL_PAYMENTS|FEES|AUTO|ERIPT] - Operation TYPE
    AUTO               - Add positive payment and get negative from list
  IMPORT_RULE=         - for payments import type id
$import_rules
  EMAIL_CHECK=...      - Check E-mail for documents. E-mail box number. Default read all mailboxes with import rule.
  FTP_CHECK=...        - Check files from ftp. FTP  servers. Default check all servers with import rule.
  BACKUP_FILES=[DIR]   - Backup ftp files
  SKIP_CROSSMODULES_CALLS - Skip cros modules calls
  METHOD=[0..]         - Method for fees or payments
  PAYSYS_EXT_ID=1      - Combine EXT_ID like PAYSYS_EXT_ID with wildcard (DATE*EXT_ID)
  FILE=                - Import FILE
  DATE=                - Import Date
  DEBUG=1,2..5         - Debug Mode
  DECODE=              - Decode from other charsets
    win2koi
    koi2win
    win2iso
    iso2win
    win2dos
    dos2win
  PLUGIN=...           - Run plugin
  MAIL=...             - Send a mail with all users info
  SKIP_ROWS=1          - Skip first row
  help                 - this help

[END]
}

1;
