#!perl

=head1 NAME
  Netblock
=name2 SYNOPSYS
  Control of Netblock
=cut

use strict;
use warnings FATAL => 'all';
use Netblock;
use Abills::Base qw(ip2int);

our (
  $db,
  $admin,
  %conf,
  $html,
  %lang,
  @bool_vals
);

my $Netblock = Netblock->new( $db, $admin, \%conf );

#**********************************************************
=head2 netblock_main()

=cut
#**********************************************************
sub netblock_main {

  my $FIELDS = 'BLOCKTYPE,HASH,INCTIME,DBTIME';
  $LIST_PARAMS{ID} = $FORM{ID};
  $pages_qs .= ($FORM{PARAM}) ? "&PARAM=$FORM{PARAM}" : q{};
  my $param = $FORM{PARAM} || 'netblock_main';
  if ($param) {
    $LIST_PARAMS{TABLE} = $param;
    if ($param eq 'netblock_ip') {
      #    $LIST_PARAMS{GROUP} = 'ip';
      $LIST_PARAMS{IP} = ip2int($FORM{NAME}) || '_SHOW';
      $FIELDS = 'IP';
    }
    elsif ($param eq 'netblock_domain') {
      #    $LIST_PARAMS{GROUP} = 'name';
      $LIST_PARAMS{NAME} = $FORM{NAME} || '_SHOW';
      $FIELDS = 'DOMAIN';
    }
    elsif ($param eq 'netblock_domain_mask') {
      #    $LIST_PARAMS{GROUP} = 'mask';
      $LIST_PARAMS{MASK} = $FORM{NAME} || '_SHOW';
      $FIELDS = 'DOMAIN-MASK';
    }
    elsif ($param eq 'netblock_url') {
      #    $LIST_PARAMS{GROUP} = 'url';
      $LIST_PARAMS{URL} = $FORM{NAME} || '_SHOW';
      #if ($FORM{NAME}){$LIST_PARAMS{URL} = $FORM{NAME}};
      $FIELDS = 'URL';
    }
    #$FIELDS .= 'SKIP';
  }

  $Netblock->{LNG_ACTION}=$lang{ADD};
  $Netblock->{ACTION}='add';

  if($FORM{add}) {
    $Netblock->add(\%FORM);
    if(! $Netblock->{errno}) {
      $html->message('info', $lang{INFO}, "$lang{CHANGED}");
    }
  }
  elsif($FORM{change}) {
    $Netblock->change(\%FORM);
    if(! $Netblock->{errno}) {
      $html->message('info', $lang{INFO}, "$lang{CHANGED}");
    }
  }
  elsif($FORM{chg}) {
    $Netblock->info({ ID => $FORM{chg} });
    if(! $Netblock->{errno}) {
      $FORM{add_form}=1;
      $html->message('info', $lang{INFO}, "$lang{CHANGE}");
      $Netblock->{LNG_ACTION} = $lang{CHANGE};
      $Netblock->{ACTION} = 'change';
    }
  }
  elsif($FORM{del} && $FORM{COMMENTS}) {
    $Netblock->del(\%FORM);
    if(! $Netblock->{errno}) {
      $html->message('info', $lang{INFO}, "$lang{DELETED}");
    }
  }

  _error_show($Netblock);

  if($FORM{add_form}) {
    $Netblock->{BLOCKTYPE_SEL} = $html->form_select(
      'BLOCKTYPE',
      {
        SELECTED => $FORM{FILTER_FIELD},
        SEL_HASH => { 'domain' => 'domain' },
        NO_ID    => 1,
      }
    );

    $html->tpl_show(_include('netblock_rule_add', 'Netblock'),
      { %$Netblock });
  }
  else {
    my @header_arr = (
      "$lang{MAIN}:index=$index",
      "IP:index=$index&PARAM=netblock_ip",
      "DOMAIN:index=$index&PARAM=netblock_domain",
      "URL:index=$index&PARAM=netblock_url",
      "DOMAIN-MASK:index=$index&PARAM=netblock_domain_mask"
    );
    my $buttons_list = $html->table_header(\@header_arr, { TABS => 1 });

    my $search_panel = $html->form_main(
      {
        CONTENT => 'ID:  ' . $html->form_input('ID', '')
          . ' URL:  ' . $html->form_input('NAME', $FORM{NAME}) .
          $html->form_input('SHOW', $lang{SEARCH}, { TYPE => 'submit' }),
        HIDDEN  => {
          'index' => $index,
        },
        NAME    => 'netblock_search_panel',
        ID      => 'netblock_search_panel',
        class   => 'navbar-form navbar-left',
      }
    );

    print $buttons_list . $html->element('div', $search_panel, { class => 'navbar navbar-default' });
  }

  if($FORM{NAME}) {
    $LIST_PARAMS{HASH} = "*$FORM{NAME}*";
  }

  if($FORM{id}) {
    $LIST_PARAMS{ID} = $FORM{id};
    if($param ne 'netblock_main') {
      $FIELDS .= 'DOMAIN,IP,URL';
    }
  }

  result_former( {
    INPUT_DATA      => $Netblock,
    FUNCTION        => '_list',
    BASE_FIELDS     => 0,
    DEFAULT_FIELDS  => "ID,$FIELDS",
    FUNCTION_FIELDS => 'change,del',
    SKIP_USER_TITLE => 1,
    EXT_FIELDS      => 0,
    EXT_TITLES      => {
      id        => 'ID',
      blocktype => $lang{BLOCKTYPE},
      inctime   => $lang{DATE},
      dbtime    => $lang{LOCK_DATE},
      hash      => 'HASH'
    },
    FILTER_COLS => {
      hash => 'netblock_filter',
    id   => 'search_link:netblock_main:,id',
    },
    TABLE           => {
      width   => '100%',
      caption => "Netblock",
      ID      => 'NETBLOCK_LIST',
      qs      => $pages_qs,
      EXPORT  => 1,
      MENU    => "$lang{ADD}:index=$index&add_form=1:add",
      SHOW_FULL_LIST => 1,
    },
    MAKE_ROWS       => 1,
    TOTAL           => 1,
    SEARCH_FORMER   => 1,
    MODULE          => 'Netblock',
  } );

  return 1;
}

#**********************************************************
=head2 netblock_filter()

=cut
#**********************************************************
sub netblock_filter {
  my($value) = @_;

  $value = $html->button($value, '', { GLOBAL_URL => 'http://'.$value });

  return $value;
}

1;
