#!perl
=head1 NAME
  3play - module for connecting Internet, IPTV and VOIP tarifs in one
  Error ID: 13xx
=cut

=head1 Synopsis
  This module give you opportunity to connect Internet, IPTV and VOIP tarif plans in one package.

	Capabilities:
		- Grouping of services
		- Maintaining packet service reports
=cut

=head1 Usage

=cut

use strict;
use warnings FATAL => 'all';

use Triplay;
use Triplay::Services;
use Tariffs;
use Abills::Base qw(expire_date);

our (
  $db,
  %lang,
  $admin,
  $users,
  $user,
  %permissions,
  %ADMIN_REPORT
);

our Abills::HTML $html;

my $Tariffs = Tariffs->new($db, \%conf, $admin);
my $Triplay = Triplay->new($db, $admin, \%conf);


if(%ADMIN_REPORT) {
  require Triplay::Periodic;
}

if ($user && $user->{UID}) {
  require Triplay::User_portal;
}

require Triplay::Users;


#**********************************************************
=head2 triplay_tp($attr) - main module function

  Arguments:


  Returns:

=cut
#**********************************************************
sub triplay_tp {

  require Control::Services;

  $Triplay->{ACTION} = 'add';
  $Triplay->{ACTION_LNG} = $lang{ADD};
  $FORM{SMALL_DEPOSIT_ACTION} = -1;
  if ($FORM{add}) {
    if (! $FORM{NAME}) {
      $html->message('err', $lang{ERROR}, $lang{ERR_WRONG_NAME});
    }
    else {
      $Tariffs->add({ %FORM, MODULE => 'Triplay' });
      if (!$Tariffs->{errno}) {
        $Triplay->tp_add({ %FORM, TP_ID => $Tariffs->{TP_ID} });
      }

      if (!$Triplay->{errno}) {
        $html->message('info', $lang{INFO}, "$lang{TARIF_PLAN} $lang{ADDED}");
      }
    }
  }
  elsif ($FORM{change}) {
    $Triplay->tp_change({ %FORM, ID => $FORM{chg} });

    if (!$Triplay->{errno}) {
      $html->message('info', $lang{SUCCESS}, "$lang{TARIF_PLAN} $lang{CHANGED}");
      $Tariffs->change($Triplay->{TP_ID}, { %FORM, TP_ID => $Triplay->{TP_ID} });
    }

    $Triplay->{ACTION} = 'change';
    $Triplay->{ACTION_LNG} = $lang{CHANGE};
  }
  elsif ($FORM{chg}) {
    $Triplay->{ACTION} = 'change';
    $Triplay->{ACTION_LNG} = $lang{CHANGE};
    $Triplay->tp_info({ ID => $FORM{chg} });

    _error_show($Triplay);
  }
  elsif ($FORM{TP_ID}) {
    $Triplay->{ACTION} = 'change';
    $Triplay->{ACTION_LNG} = $lang{CHANGE};
    $Triplay->tp_info({ TP_ID => $FORM{TP_ID} });

    _error_show($Triplay);
  }
  elsif ($FORM{del} && $FORM{COMMENTS}) {
    $Triplay->tp_del({ %FORM, ID => $FORM{del} });

    if (!$Triplay->{errno}) {
      $html->message('info', $lang{INFO}, "$lang{DELETED} $FORM{del}");
    }
  }

  _error_show($Triplay);

  my $iptv_select = sel_tp({
    MODULE  => 'Iptv',
    IPTV_TP => $Triplay->{IPTV_TP},
    SELECT  => 'IPTV_TP',
    USER_INFO => $users,
    EX_PARAMS   => {
      MAIN_MENU => get_function_index('iptv_tp'),
      MAIN_MENU_ARGV => ($Triplay->{IPTV_TP}) ? "TP_ID=$Triplay->{IPTV_TP}" : ''
    }
  });
  my $internet_select = sel_tp({
    MODULE      => 'Internet',
    USER_INFO   => $users,
    INTERNET_TP => $Triplay->{INTERNET_TP},
    SELECT      => 'INTERNET_TP',
    EX_PARAMS   => {
      MAIN_MENU => get_function_index('internet_tp'),
      MAIN_MENU_ARGV => ($Triplay->{INTERNET_TP}) ? "TP_ID=$Triplay->{INTERNET_TP}" : ''
    }
  });
  my $voip_select = sel_tp({
    MODULE    => 'Voip',
    USER_INFO => $users,
    #TP_ID  => $Triplay->{VOIP_TP},
    VOIP_TP   => $Triplay->{VOIP_TP},
    SELECT    => 'VOIP_TP',
    EX_PARAMS   => {
      MAIN_MENU => get_function_index('voip_tp'),
      MAIN_MENU_ARGV => ($Triplay->{VOIP_TP}) ? "TP_ID=$Triplay->{VOIP_TP}" : ''
    }
  });

  use Abon;
  my $Abon = Abon->new($db, $admin, \%conf);
  my $abon_select = $html->form_select('ABON_TP', {
    SELECTED       => $Triplay->{ABON_TP} || 0,
    SEL_LIST       => $Abon->tariff_list_former({ TP_NAME=>'_SHOW', COLS_NAME => 1, PAGE_ROWS => 60000 }),
    SEL_VALUE      => 'tp_name',
    NO_ID          => 1,
    SEL_OPTIONS    => { '' => '--' },
    MAIN_MENU      => get_function_index('abon_tariffs'),
    MAIN_MENU_ARGV => ($Triplay->{ABON_TP}) ? "TP_ID=$Triplay->{ABON_TP}" : ''
  });

  $Triplay->{SEL_METHOD} = $html->form_select('FEES_METHOD', {
    SELECTED       => $Triplay->{FEES_METHOD} || 1,
    SEL_HASH       => get_fees_types(),
    NO_ID          => 1,
    SORT_KEY       => 1,
    SEL_OPTIONS    => { 0 => '' },
    MAIN_MENU      => get_function_index('form_fees_types'),
    CHECKBOX       => 'create_fees_type',
    CHECKBOX_TITLE => $lang{CREATE}
  });

  my %payment_types = (
    0 => $lang{PREPAID},
    1 => $lang{POSTPAID},
    2 => $lang{GUEST}
  );

  $Triplay->{PAYMENT_TYPE_SEL} = $html->form_select('PAYMENT_TYPE', {
    SELECTED => $Triplay->{PAYMENT_TYPE} || 0,
    SEL_HASH => \%payment_types,
    NO_ID    => 1
  });

  $Triplay->{NEXT_TARIF_PLAN_SEL} = sel_tp({
    SELECT          => 'NEXT_TARIF_PLAN',
    NEXT_TARIF_PLAN => $Triplay->{NEXT_TARIF_PLAN},
    MAIN_MENU       => 'triplay_tp',
    MODULE          => 'Triplay'
  });

  $Triplay->{REDUCTION_FEE}    = ($Triplay->{REDUCTION_FEE})      ? 'checked' : '';
  $Triplay->{PERIOD_ALIGNMENT} = ($Triplay->{PERIOD_ALIGNMENT} || $FORM{PERIOD_ALIGNMENT}) ? 'checked' : '';

  $html->tpl_show(_include('triplay_tp', 'Triplay'), {
    %$Triplay,
    INTERNET => $internet_select,
    IPTV     => $iptv_select,
    VOIP     => $voip_select,
    ABON     => $abon_select,
    ID       => $Triplay->{TRIPLAY_TP_ID}
  });

  result_former({
    INPUT_DATA      => $Triplay,
    FUNCTION        => 'tp_list',
    BASE_FIELDS     => 2,
    DEFAULT_FIELDS  => 'ID,NAME,MONTH_FEE,DAY_FEE,INTERNET_NAME,IPTV_NAME,VOIP_NAME,ABON_NAME,COMMENT',
    FUNCTION_FIELDS => 'change, del',
    EXT_TITLES      => {
      id              => 'ID',
      name            => $lang{NAME},
      internet_name   => $lang{INTERNET},
      iptv_name       => $lang{TV},
      voip_name       => $lang{VOIP},
      month_fee       => $lang{MONTH_FEE},
      day_fee         => $lang{DAY_FEE},
      comment         => $lang{COMMENTS},
      internet_name   => $lang{INTERNET},
      iptv_name       => $lang{TV},
      voip_name       => $lang{VOIP},
      abon_name       => $lang{ABON},
      age             => $lang{AGE},
      next_tarif_plan => "$lang{NEXT} $lang{TARIF_PLAN}"
    },
    TABLE           => {
      width   => '100%',
      caption => $lang{TARIF_PLANS},
      qs      => $pages_qs,
      ID      => 'TRIPLAY_TP',
      EXPORT  => 1,
      MENU    => "$lang{ADD}:index=" . get_function_index('triplay_tp') . ':add' . ";",
    },
    MAKE_ROWS       => 1,
    SEARCH_FORMER   => 1,
    MODULE          => 'Triplay',
    TOTAL           => 1
  });

  return 1;
}

1