#!perl
=head1 NAME

  3play - module for connecting Internet, IPTV and VOIP tariffs in one
  Error ID: 13xx
=cut

=head1 Synopsis

  This module give you opportunity to connect Internet, IPTV and VOIP tariff plans in one package.

	Capabilities:
		- Grouping of services
		- Maintaining packet service reports
=cut

=head1 Usage

=cut

use strict;
use warnings FATAL => 'all';

our Abills::HTML $html;

our (
  $db,
  $users,
  $admin,
  $user,
  %permissions,
  %ADMIN_REPORT
);

if (%ADMIN_REPORT) {
  require Triplay::Periodic;
}

if ($user && $user->{UID}) {
  require Triplay::User_portal;
}

if ($permissions{4}) {
  require Triplay::Configure;
}

require Triplay::Users;

1;
