#!perl
=head1 NAME

  Revisor managment module

=cut


use strict;
use warnings FATAL => 'all';

use Revisor::db::Revisor;
use Dv_Sessions;
use Abills::Base qw/in_array _bp/;

our(
  %lang,
  $html,
  $admin,
  $db,
  %conf,
  @MODULES,
);

my $Revisor = Revisor->new($db, $admin, \%conf);
my $Sessions =();
if (in_array( 'Internet', \@MODULES )) {
  require Internet::Sessions;
  $Sessions = Internet::Sessions->new($db, $admin, \%conf);
}
else {
  $Sessions = Dv_Sessions->new($db, $admin, \%conf);
}

#**********************************************************
=head2 revisor_user_list($attr)

=cut
#**********************************************************
sub revisor_user_list {
# print "Content-Type:text/html\n\n";
# $Sessions->{debug} = 1;

  my $pages_qs = '';
 
  if ($FORM{info}) {
    my $info = $Revisor->user_list({
      FIO           => '_SHOW',
      UID           => '_SHOW',
      COMPANY_ID    => '_SHOW',
      PHONE         => '_SHOW',
      ADDRESS_FULL  => '_SHOW',
      LOGIN         => $FORM{info},
      COMPANY_NAME  => '_SHOW',
      PASPORT_NUM   => '_SHOW',
      PASPORT_DATE  => '_SHOW',
      PASPORT_GRANT => '_SHOW',
      
      COLS_NAME     => 1,
      COLS_UPPER    => 1,
    });
    _error_show($Revisor);
    
    my $dv_info = '';
    if (in_array( 'Internet', \@MODULES )) {
      $dv_info = $Revisor->revisor_internet_list({ IP_NUM => '_SHOW', UID => $info->[0]->{UID} });
    }
    else {
      $dv_info = $Revisor->revisor_dv_list({ IP_NUM => '_SHOW', UID => $info->[0]->{UID} });
    }
    
    if($dv_info && scalar(@$dv_info) > 0 && $dv_info->[0]->{ip_num}) {
      $info->[0]->{STATIC_IP} = $dv_info->[0]->{ip_num};
      $info->[0]->{STATIC_IP_TEXT} = "$lang{STATIC} IP";
    }
    else {
      $info->[0]->{STATIC_IP_HIDDEN} = "hidden";
    }
    
    my $session_info = $Sessions->online({ 
      UID         => $info->[0]->{UID}, 
      CLIENT_IP   => '_SHOW',
      NAS_NAME    => '_SHOW',
      COLS_NAME   => 1,
      COLS_UPPER  => 1,
    });

    if ($Sessions->{TOTAL}) {
      $info->[0]->{STATUS} = "Online";
      $info->[0]->{IP_NUM} = $session_info->[0]->{client_ip};
      $info->[0]->{NAS_NAME} = $session_info->[0]->{nas_name};
      $info->[0]->{IP_TEXT} = "IP";
    }
    else {
      $info->[0]->{STATUS} = "Offline";
      my $sessions_list = $Sessions->list({
        LOGIN        => $FORM{info},
        IP           => '_SHOW',
        START        => '_SHOW',
        END          => '_SHOW',
        
        SORT         => 2,
        DESC         => 'DESC',
        COLS_NAME    => 1,
        COLS_UPPER   => 1,
      });
      
      $info->[0]->{IP_NUM} = $sessions_list->[0]->{ip};
      $info->[0]->{IP_TEXT} = "Последний IP";
    }
    
    $info->[0]->{BUTTON} = $html->button("$lang{SESSIONS}", "index=40&LOGIN=$info->[0]->{LOGIN}", {ex_params => "class='btn btn-primary'"});
    $html->tpl_show(_include('revisor_user_info', 'Revisor'), $info->[0]);
  }
  
  # print 'Content-Type:text/html\n\n';
  # $Revisor->{debug} = 1;
  else {
    $html->tpl_show(_include('revisor_user_search', 'Revisor'), {
      %FORM,
      DATE_FIELD => 'hidden',
      IP_FIELD => 'hidden',
      TITLE => $lang{USERS}, 
    });
    my $users_list = $Revisor->user_list({
      FIO           => '_SHOW',
      UID           => '_SHOW',
      COMPANY_ID    => '_SHOW',
      PHONE         => '_SHOW',
      ADDRESS_FULL  => '_SHOW',
      LOGIN         => '_SHOW',
      COMPANY_NAME  => '_SHOW',

      COLS_NAME     => 1,
      COLS_UPPER    => 1,
      PAGE_ROWS     => 9999,
      SORT          => $FORM{sort} || '',
      DESC          => $FORM{desc} || '',
    });
    
    $pages_qs = "&COMPANY_NAME=" . ($FORM{COMPANY_NAME} || '')
      . "&FIO=" . ($FORM{FIO} || '')
      . "&LOGIN=" . ($FORM{LOGIN} || '')
      . "&ADDRESS_FULL=" . ($FORM{ADDRESS_FULL} || '');
    
    my $table = $html->table({
      width      => '100%',
      caption    => $lang{USERS},
      title      => [ $lang{LOGIN}, $lang{FIO}, $lang{PHONE}, '', $lang{ADDRESS}],
      ID         => 'Users',
      qs         => $pages_qs,
      
    });

    foreach my $user_line (@$users_list) {
      next if ($FORM{COMPANY_NAME} && !$user_line->{COMPANY_NAME});
      next if ($FORM{COMPANY_NAME} && !($user_line->{COMPANY_NAME} =~ m/$FORM{COMPANY_NAME}/));
      next if ($FORM{LOGIN} && !($user_line->{LOGIN} =~ m/$FORM{LOGIN}/));
      next if ($FORM{FIO} && !$user_line->{FIO});
      next if ($FORM{FIO} && !($user_line->{FIO} =~ m/$FORM{FIO}/));
      next if ($FORM{ADDRESS_FULL} && !$user_line->{ADDRESS_FULL});
      next if ($FORM{ADDRESS_FULL} && !($user_line->{ADDRESS_FULL} =~ m/$FORM{ADDRESS_FULL}/));
      $table->addrow(
        $html->button($user_line->{LOGIN}, "index=$index&info=$user_line->{LOGIN}"),
        $user_line->{COMPANY_ID} ? $user_line->{COMPANY_NAME} : $user_line->{FIO},
        $user_line->{PHONE},
        '',
        $user_line->{ADDRESS_FULL}
      );
    }
    print $table->show();
  }
  return 1;
}

#**********************************************************
=head2 revisor_online_list($attr)

=cut
#**********************************************************

sub revisor_online_list {

  $html->tpl_show(_include('revisor_user_search', 'Revisor'), { %FORM, DATE_FIELD => 'hidden', TITLE => "Online $lang{SEARCH}" });

  my $online_list = $Sessions->online({ 
      UID           => '_SHOW',
      CID           => '_SHOW',
      LOGIN         => '_SHOW',
      CLIENT_IP     => '_SHOW',
      NAS_NAME      => '_SHOW',
      FIO           => '_SHOW',
      DURATION      => '_SHOW',
      COMPANY_ID    => '_SHOW',
      COMPANY_NAME  => '_SHOW',
      ADDRESS_FULL  => '_SHOW',
      
      PAGE_ROWS     => 999,
      COLS_NAME     => 1,
      COLS_UPPER    => 1,
    });
    
  my $table = $html->table({
    width       => '100%',
    caption     => "Online $lang{USERS}",
    title_plain => [ "IP", $lang{LOGIN}, $lang{FIO}, $lang{ADDRESS}, "$lang{TIME} online", "CID", $lang{NAS}],
    ID          => 'Online',
  });
  # _bp('', $online_list, {HEADER => 1});
  foreach my $user_line (@$online_list) {
    next if ($FORM{COMPANY_NAME} && !$user_line->{company_id});
    next if ($FORM{COMPANY_NAME} && !($user_line->{company_name} =~ m/$FORM{COMPANY_NAME}/));
    next if ($FORM{LOGIN} && !($user_line->{login} =~ m/$FORM{LOGIN}/));
    next if ($FORM{FIO} && !($user_line->{fio} =~ m/$FORM{FIO}/));
    next if ($FORM{CID} && !($user_line->{CID} =~ m/$FORM{CID}/));
    next if ($FORM{ADDRESS_FULL} && !$user_line->{address_full});
    next if ($FORM{ADDRESS_FULL} && !($user_line->{address_full} =~ m/$FORM{ADDRESS_FULL}/));
    next if ($FORM{IP_NUM} && !($user_line->{client_ip} =~ m/$FORM{IP_NUM}/));
    
    $table->addrow(
      $html->button($user_line->{client_ip}, "index=30&IP_NUM=$user_line->{client_ip}"),
      $html->button($user_line->{login}, "index=20&info=$user_line->{login}"),
      $user_line->{company_id} ? $user_line->{company_name} : $user_line->{fio},
      $user_line->{address_full},
      $user_line->{duration},
      $user_line->{CID},
      $user_line->{nas_name}
    );
  }
  
  print $table->show();
  
  return 1;
}

#**********************************************************
=head2 revisor_user_search($attr)

=cut
#**********************************************************

sub revisor_user_search {

  my ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime();
    
  $FORM{FROM_DATE} //= sprintf("%04d-%02d-%02d", 1900+$year, $mon+1, 1);
  $FORM{TO_DATE} //= sprintf("%04d-%02d-%02d", 1900+$year, $mon+1, $mday);

  $html->tpl_show(_include('revisor_user_search', 'Revisor'), { %FORM, TITLE => "$lang{SEARCH}" });
  
  $pages_qs = "&COMPANY_NAME=" . ($FORM{COMPANY_NAME} || '')
      . "&FIO=" . ($FORM{FIO} || '')
      . "&FROM_DATE=$FORM{FROM_DATE}"
      . "&TO_DATE=$FORM{TO_DATE}"
      . "&ADDRESS_FULL=" . ($FORM{ADDRESS_FULL} || '');
  
  my $sessions_list = $Sessions->list({
    LOGIN        => '_SHOW',
    CID          => '_SHOW',
    IP           => '_SHOW',
    START        => '_SHOW',
    END          => '_SHOW',
    FIO          => '_SHOW',
    COMPANY_NAME => '_SHOW',
    ADDRESS_FULL => '_SHOW',
    FROM_DATE    => $FORM{FROM_DATE},
    TO_DATE      => $FORM{TO_DATE},
    
    PAGE_ROWS     => 999,
    COLS_NAME     => 1,
    COLS_UPPER    => 1,
  });
  
  my $table = $html->table({
    width       => '100%',
    caption     => $lang{SESSIONS},
    title_plain => [ "IP", $lang{LOGIN}, $lang{FIO}, $lang{ADDRESS}, "CID", $lang{START}, $lang{END}],
    ID          => 'Sessions',
  });
  # use Abills::Base qw/_bp/;
  # print 'Content-Type:text/html\n\n';
  # _bp('', $sessions_list, {HEADER => 1});
  foreach my $user_line (@$sessions_list) {
    next if ($FORM{IP_NUM} && !($user_line->{IP} =~ m/$FORM{IP_NUM}/));
    next if ($FORM{COMPANY_NAME} && !$user_line->{COMPANY_ID});
    next if ($FORM{COMPANY_NAME} && !($user_line->{COMPANY_NAME} =~ m/$FORM{COMPANY_NAME}/));
    next if ($FORM{LOGIN} && !($user_line->{LOGIN} =~ m/$FORM{LOGIN}/));
    next if ($FORM{FIO} && !($user_line->{FIO} =~ m/$FORM{FIO}/));
    next if ($FORM{CID} && !($user_line->{CID} =~ m/$FORM{CID}/));
    next if ($FORM{ADDRESS_FULL} && !$user_line->{ADDRESS_FULL});
    next if ($FORM{ADDRESS_FULL} && !($user_line->{ADDRESS_FULL} =~ m/$FORM{ADDRESS_FULL}/));
    $table->addrow(
      $html->button($user_line->{IP}, "index=$index&$pages_qs&IP_NUM=$user_line->{IP}"),
      $html->button($user_line->{LOGIN}, "index=$index&$pages_qs&LOGIN=$user_line->{LOGIN}"),
      $user_line->{COMPANY_ID} ? $user_line->{COMPANY_NAME} : $user_line->{FIO},
      $user_line->{ADDRESS_FULL},
      $user_line->{CID},
      $user_line->{START},
      $user_line->{END},
  )};
  print $table->show();

}
1
