SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';
DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION IF NOT EXISTS `DECODE`(`ENCR` BLOB, `KEY` VARCHAR(100)) RETURNS varchar(100) CHARSET utf8mb4
  DETERMINISTIC
    return cast(AES_DECRYPT(`ENCR`,sha2(`KEY`,256)) as char(200))$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION IF NOT EXISTS `ENCODE`(`STR` VARCHAR(200), `KEY` VARCHAR(100)) RETURNS blob
  DETERMINISTIC
    return AES_ENCRYPT(`STR`,sha2(`KEY`,256))$$
DELIMITER ;
