$lang{EXTRA_TRAFIC}   = 'Додатковий трафік';
$lang{FILES}          = 'Файли';
$lang{AMOUNT}         ='Абонплата';
$lang{TIME_FOR_LINK}  = 'Час життя посилання';
$lang{TIME_FOR_FILE}  = 'Час доступу до файлу';
$lang{BUY}            = 'Купити';
$lang{GET_LINK}       = 'Отримати посилання';
$lang{FILE_NOT_ADDED} = 'Файл не доданий';
$lang{FILE_NOT_DELETED} = 'Файл не знищений';
$lang{FILE_NOT_CHANGED} = 'Файл не змінений';
$lang{DAYS}             = 'Днів';
$lang{SUCCESS_BUY}      = 'Успішно оплатили покупку файла до ';
$lang{DATE_TO}          = 'Завантаження доступно до ';
$lang{SECONDS}          = 'Секунд';
$lang{NOT_ENOUGH_MONEY} = 'Недостатньо коштів';
$lang{VERSION}          = 'Версія';
$lang{DOWNLOADS}        = 'Скачувань';
$lang{TIME_FOR_REMIND}  = 'Попереджувати за';
1