#!perl

=head1 NAME

  Crm

=cut

use strict;
use warnings FATAL => 'all';
use Crm::db::Crm;
use Abills::Base qw(days_in_month mk_unique_value in_array);
use Abills::Misc;
use Admins;
use Employees;
use Abills::Sender::Core;
use Crm::Leads;
require Abills::Defs;
our ($db, $admin, %conf, %lang, $html, @MONTHES, %permissions);

our Crm $Crm = Crm->new($db, $admin, \%conf);

our @PRIORITY = ($lang{LOW}, $lang{NORMAL}, $lang{HIGH});

#**********************************************************
=head2 crm_today_actions()

  Arguments:
     -

  Returns:

=cut
#**********************************************************
sub crm_today_actions {
  my $today_actions = $Crm->progressbar_comment_list({
    AID          => $admin->{AID},
    PLANNED_DATE => $DATE,
    ACTION_ID    => '>0',
    STATUS       => '0',
    LEAD_ID      => '_SHOW',
    ACTION       => '_SHOW',
    LEAD_FIO     => '_SHOW',
    COLS_NAME    => 1,
    PAGE_ROWS    => 999999
  });

  my $actions_table = $html->table(
    {
      width   => '100%',
      caption => "$lang{ACTION} CRM",
      title   => [ "$lang{FIO}", "$lang{ACTION}", "$lang{DATE}", '' ],
      ID      => 'CRM_TODAY_ACTION',
    }
  );

  my $leads_function_index = get_function_index('crm_lead_info');
  foreach my $action (@$today_actions) {
    my $lead_button = $html->button("$lang{SHOW}", "index=$leads_function_index&LEAD_ID=$action->{lead_id}");
    $actions_table->addrow($action->{lead_fio}, $action->{action}, $action->{planned_date}, $lead_button);
  }

  return $actions_table->show();
}

#**********************************************************
=head2 crm_sales_funnel_widget()

  Arguments:
     -

  Returns:

=cut
#**********************************************************
sub crm_sales_funnel_widget {
  return crm_sales_funnel({RETURN_TABLE => 1});
}

#**********************************************************
=head2 paysys_start_page($attr)

  Arguments:


  Returns:

=cut
#**********************************************************
sub crm_start_page {
  #my ($attr) = @_;

  my %START_PAGE_F = (
    'crm_today_actions'       => "$lang{TODAY} $lang{ACTION}",
    'crm_sales_funnel_widget' => $lang{SALES_FUNNEL},
  );

  return \%START_PAGE_F;
}

1