$lang{OPERATION_PAYMENT}='Ціна операції';
$lang{ORDER_PRINT}='Відправити карточки на друк';
$lang{ACTIVATION_PAYMENTS}='Оплата після активації';
$lang{ERR_SELECT_TARIF_PLAN}='Виберіть тарифний план';
$lang{ERR_COMPANY_DISABLE}='Поповнення компаніям заборонено';
$lang{COMMISSION}='Комісія';
$lang{ERR_TRY_AGAIN}='виникла помилка. Спробуйте ще раз';
$lang{DILLERS_USE}='Відправлено ділерам';
$lang{TRANSFERRED_TO_PRODUCTION}='Передано в виробництво';