$lang{ERR_MOBILE_UNFILLED_MANDATORY_CATEGORIES} = 'Mandatory categories are not filled in: %CATEGORIES%';
$lang{ERR_MOBILE_LIFECELL_API} = 'Error in API operation';
$lang{ERR_MOBILE_TP_ALREADY_ACTIVATED} = 'Tariff plan already activated';
$lang{ERR_MOBILE_PHONE_NOT_FOUND} = 'Activated phone number not found';
$lang{ERR_MOBILE_TP_NOT_FOUND} = 'Tariff plan not found';
$lang{ERR_MOBILE_SERVICES_NOT_FOUND} = 'No services are selected in the tariff plan';
$lang{ERR_MOBILE_PHONE_ALREADY_ACTIVATED} = 'Phone number already activated';
$lang{ERR_MOBILE_WAIT_PHONE_NUMBER_ACTIVATION} = 'Wait for confirmation of phone number activation';
$lang{ERR_MOBILE_WRONG_PARAMETERS} = 'Wrong parameters';
$lang{ERR_MOBILE_PHONE_ALREADY_DEACTIVATED} = 'The phone number has already been deactivated';
$lang{ERR_MOBILE_WAIT_SERVER_RESPONSE} = 'Wait for the service response';
$lang{ERR_MOBILE_FUNCTION_NOT_FOUND} = 'Function not found';

$lang{MOBILE_COMMUNICATION} = 'Mobile communication';
$lang{PHONE_ACTIVATE} = 'Activate phone number';
$lang{MOBILE_CATEGORIES} = 'Categories';
$lang{MOBILE_CATEGORY} = 'Category';
$lang{MOBILE_MAIN_CATEGORY} = 'Main category';
$lang{MOBILE_MANDATORY} = 'Mandatory';
$lang{MOBILE_SERVICES} = 'Services';
$lang{MOBILE_STATUS_NUMBER} = 'Status of the phone number';
$lang{MOBILE_STATUS_TARIFF_PLAN} = 'Status of the tariff plan';
$lang{MOBILE_ACTIVATION_DATE} = 'Activation date';
$lang{MOBILE_WAIT_CONFIRMATION_TARIFF} = 'Wait for confirmation of tariff plan activation';
$lang{MOBILE_WAIT_CONFIRMATION_NUMBER} = 'Wait for confirmation of phone number activation';
$lang{MOBILE_CONFIRM} = 'Confirmation';
$lang{MOBILE_CONFIRMATION_ACTIVATION} = 'Activation confirmation of phone number';
$lang{MOBILE_WAIT_NUMBER_DEACTIVATE} = 'Wait for the number to be deactivated';
$lang{MOBILE_PHONE_DEACTIVATE} = 'Phone number deactivation';

$lang{MOBILE_LOGS} = 'Mobile logs';
$lang{MOBILE_TRANSACTION_ID} = 'Transaction ID';
$lang{MOBILE_RESPONSE} = 'Response';
$lang{MOBILE_CALLBACK} = 'Callback';
$lang{MOBILE_CALLBACK_DATE} = 'Callback date';

$lang{MOBILE_ALL_ACTIVATION_ATTEMPTS_USED} = 'All %ATTEMPTS% activation attempts used';
$lang{MOBILE_METHOD} = 'Method';
$lang{MOBILE_ACTIVATION_ATTEMPTS_COUNT} = 'Activation attempts count';
