get:
  tags:
    - crm
  summary: Список источников
  operationId: getCrmSourcesList
  parameters:
    - name: id
      in: query
      description: Id действия
      schema:
        type: boolean
        default: true
    - name: name
      in: query
      description: Название источника
      schema:
        type: boolean
        default: false
    - name: comments
      in: query
      description: Комментарий
      schema:
        type: boolean
        default: false
    - $ref: "#/components/parameters/desc"
    - $ref: "#/components/parameters/pageRows"
    - $ref: "#/components/parameters/pg"
    - $ref: "#/components/parameters/sort"
  responses:
    200:
      description: успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/sourceList.yaml"
  security:
    - KEY: [ ]