#!/usr/bin/perl
=head1 NAME

 Push report log

=cut

use strict;
use warnings FATAL => 'all';
use Contacts;
use Admins;

our (
  $db,
  $admin,
  %conf,
  %lang
);

my $Contacts = Contacts->new($db, $admin, \%conf);
my $Admins = Admins->new($db, \%conf);
our Abills::HTML $html;

#**********************************************************
=head2 push_log()

  Print logs of Push

=cut
#**********************************************************
sub push_log {

  my ($year, $month, $day) = split(/-/, $DATE, 3);
  my $date_from = "$year-$month-01";
  $FORM{DATE_START} ||= $date_from;
  $FORM{DATE_END} ||= $DATE;

  my %push_status = (
    0 => $lang{SUCCESS},
    1 => $lang{ERROR},
  );

  my $admins_list = sel_admins({ HASH=>1, DISABLE => 0 });

  my $admins_sel = $html->form_select('AID', {
    SELECTED     => (defined($FORM{AID})) ? $FORM{AID} : q{},
    SEL_OPTIONS  => { '' => '' },
    SEL_HASH     => $admins_list,
    NO_ID        => 1,
  });
  my $status_sel = $html->form_select('STATUS', {
    SELECTED     => $FORM{STATUS} || q{},
    SEL_OPTIONS  => { '' => '' },
    SEL_HASH     => \%push_status,
    NO_ID        => 1,
  });
  my $datepicker = $html->form_daterangepicker({
    NAME      => 'DATE_START/DATE_END',
    FORM_NAME => 'search_form',
    VALUE     => $FORM{'DATE_START_DATE_END'},
  });

  form_search({ TPL => $html->tpl_show(_include('push_report_search', 'Push'), {
    DATEPICKER    => $datepicker,
    DATE_START    => $FORM{DATE_START},
    DATE_END      => $FORM{DATE_END},
    STATUS_SELECT => $status_sel,
    ADMINS_SELECT => $admins_sel
  }, { OUTPUT2RETURN => 1 })
  });

  if ($FORM{del} && $FORM{COMMENTS}) {
    $Contacts->push_messages_del({ ID => $FORM{del} });
    $html->message('info', $lang{SUCCESS}, $lang{DELETED}) if !$Contacts->{errno};
  }

  my ($table, undef) = result_former({
    INPUT_DATA      => $Contacts,
    FUNCTION        => 'push_messages_list',
    FUNCTION_INDEX  => $index,
    BASE_FIELDS     => 0,
    DEFAULT_FIELDS  => 'ID,TYPE_ID,TITLE,MESSAGE,CREATED,UID,AID,STATUS',
    FUNCTION_FIELDS => 'del',
    SELECT_VALUE    => {
      status => {
        0 => $lang{SUCCESS},
        1 => $lang{ERROR},
      },
      aid    => $admins_list,
    },
    EXT_TITLES      => {
      id       => 'ID',
      type_id  => $lang{TYPE},
      title    => $lang{TITLE},
      message  => $lang{MESSAGE},
      request  => $lang{REQUEST},
      response => $lang{RESPONSE},
      created  => $lang{DATE},
      status   => $lang{STATUS},
      uid      => 'UID',
      aid      => $lang{ADMIN},
    },
    SKIP_USER_TITLE => 1,
    TABLE           => {
      width   => '100%',
      caption => $lang{PUSH_LOG},
      qs      => $pages_qs,
      ID      => 'PUSH_LOG',
      pages   => $Contacts->{TOTAL},
      MENU    => "$lang{SEARCH}:index=$index&search_form=1:search;",
      EXPORT  => 1,
    },
    SKIP_USER_TITLE   => 1,
    MAKE_ROWS       => 1,
  });

  return print $table->show();
}

1;
