CREATE TABLE IF NOT EXISTS `abon_tariffs` (
  `id` SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `period` TINYINT(2) UNSIGNED NOT NULL DEFAULT '0',
  `price` DOUBLE(14, 2) UNSIGNED NOT NULL DEFAULT '0.00',
  `payment_type` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `period_alignment` TINYINT(1) NOT NULL DEFAULT '0',
  `ext_bill_account` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `nonfix_period` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `priority` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `account` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `fees_type` TINYINT(2) UNSIGNED NOT NULL DEFAULT '0',
  `create_account` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `vat` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `notification1` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `notification2` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `notification_account` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `activate_notification` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `alert` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `alert_account` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `ext_cmd` VARCHAR(240) NOT NULL DEFAULT '',
  `discount` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `manual_activate` TINYINT(1) NOT NULL DEFAULT 0,
  `user_portal` TINYINT(1) NOT NULL DEFAULT 0,
  `domain_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0,
  `service_link` VARCHAR(240) NOT NULL DEFAULT '',
  `description` VARCHAR(240) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `name` (`name`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Abon tariffs';

CREATE TABLE IF NOT EXISTS `abon_user_list` (
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `tp_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `date` DATE NOT NULL DEFAULT '0000-00-00',
  `comments` VARCHAR(240) NOT NULL DEFAULT '',
  `notification1` DATE NOT NULL DEFAULT '0000-00-00',
  `notification1_account_id` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `notification2` DATE NOT NULL DEFAULT '0000-00-00',
  `discount` DOUBLE(6, 2) NOT NULL DEFAULT '0.00',
  `create_docs` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `send_docs` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `service_count` SMALLINT(4) UNSIGNED NOT NULL DEFAULT 1,
  `manual_fee` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `fees_period` SMALLINT(4) UNSIGNED NOT NULL DEFAULT 0,
  KEY `uid` (`uid`, `tp_id`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Abon user list';
