CREATE TABLE hotspot_visits (
  id VARCHAR(32) PRIMARY KEY NOT NULL,
  first_seen DATETIME NOT NULL DEFAULT NOW(),
  browser VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN'

);

CREATE TABLE hotspot_logins (
  id INT(11) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  visit_id VARCHAR(32) NOT NULL REFERENCES hotspot_visits(`id`) ON DELETE CASCADE,
  uid INT(11) UNSIGNED NOT NULL REFERENCES users (`uid`) ,
  login_time DATETIME NOT NULL DEFAULT NOW()
);