CREATE TABLE IF NOT EXISTS `internet_log_intervals` (
  `interval_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `sent` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `recv` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `duration` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `traffic_type` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `sum` DOUBLE(14, 6) UNSIGNED NOT NULL DEFAULT '0.000000',
  `acct_session_id` VARCHAR(32) NOT NULL DEFAULT '',
  `added` TIMESTAMP NOT NULL,
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  KEY `acct_session_id` (`acct_session_id`),
  KEY `session_interval` (`acct_session_id`, `interval_id`),
  KEY `uid` (`uid`)
)
  COMMENT = 'Internet interval summary stats';


CREATE TABLE IF NOT EXISTS `internet_main` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uid` int(10) unsigned NOT NULL DEFAULT '0',
  `tp_id` smallint(6) NOT NULL DEFAULT '0',
  `logins` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `registration` date DEFAULT '0000-00-00',
  `ip` int(10) unsigned NOT NULL DEFAULT '0',
  `netmask` int(10) unsigned NOT NULL DEFAULT '4294967295',
  `filter_id` varchar(150) NOT NULL DEFAULT '',
  `speed` int(10) unsigned NOT NULL DEFAULT '0',
  `cid` varchar(200) NOT NULL DEFAULT '',
  `password` blob NOT NULL,
  `disable` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `join_service` int(10) unsigned NOT NULL DEFAULT '0',
  `turbo_mode` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `free_turbo_mode` smallint(6) unsigned NOT NULL DEFAULT '0',
  `activate` date NOT NULL DEFAULT '0000-00-00',
  `expire` date NOT NULL DEFAULT '0000-00-00',
  `login` varchar(24) NOT NULL DEFAULT '',
  `detail_stats` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `personal_tp` double(14,2) unsigned NOT NULL DEFAULT '0.00',
  `cpe_mac` varchar(200) NOT NULL DEFAULT '',
  `comments` varchar(250) NOT NULL DEFAULT '',
  `port` varchar(100) NOT NULL DEFAULT '',
  `vlan` smallint(6) NOT NULL DEFAULT '0',
  `nas_id` smallint(6) unsigned NOT NULL DEFAULT '0',
  `server_vlan` smallint(6) unsigned NOT NULL DEFAULT '0',
  `ipn_activate` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `uid` (`uid`)
) COMMENT='Internet users' ;


CREATE TABLE IF NOT EXISTS `internet_online` (
  `status` INT(3) NOT NULL DEFAULT '0',
  `user_name` VARCHAR(32) NOT NULL DEFAULT '',
  `started` DATETIME NOT NULL,
  `nas_ip_address` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `nas_port_id` INT(6) UNSIGNED NOT NULL DEFAULT '0',
  `acct_session_id` VARCHAR(32) NOT NULL DEFAULT '',
  `acct_session_time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `acct_input_octets` BIGINT(14) UNSIGNED NOT NULL DEFAULT '0',
  `acct_output_octets` BIGINT(14) UNSIGNED NOT NULL DEFAULT '0',
  `ex_input_octets` BIGINT(14) UNSIGNED NOT NULL DEFAULT '0',
  `ex_output_octets` BIGINT(14) UNSIGNED NOT NULL DEFAULT '0',
  `connect_term_reason` SMALLINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `framed_ip_address` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `framed_ipv6_prefix` VARBINARY(16) NOT NULL DEFAULT '',
  `framed_interface_id` VARBINARY(16) NOT NULL DEFAULT '',
  `lupdated` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `sum` DOUBLE(14, 6) NOT NULL DEFAULT '0.000000',
  `cid` VARCHAR(20) NOT NULL DEFAULT '',
  `connect_info` VARCHAR(35) NOT NULL DEFAULT '',
  `tp_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `nas_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `acct_input_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `acct_output_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `ex_input_octets_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `ex_output_octets_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `join_service` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `turbo_mode` VARCHAR(30) NOT NULL DEFAULT '',
  `guest` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `circuit_id` VARCHAR(25) NOT NULL DEFAULT '',
  `remote_id` VARCHAR(25) NOT NULL DEFAULT '',
  `hostname` VARCHAR(30) NOT NULL DEFAULT '',
  `switch_port` VARCHAR(11) NOT NULL DEFAULT '',
  `vlan` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `server_vlan` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `switch_mac` VARCHAR(17) NOT NULL DEFAULT '',
  `dhcp_id` TINYINT(2) NOT NULL DEFAULT '0',
  `dhcp_ends` DATETIME NOT NULL,
  `service_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  KEY `user_name` (`user_name`),
  KEY `acct_session_id` (`acct_session_id`),
  KEY `framed_ip_address` (`framed_ip_address`),
  KEY `uid` (`uid`)
) COMMENT='Internet online';


CREATE TABLE IF NOT EXISTS `internet_log` (
  `start` DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  `tp_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `duration` INT(11) NOT NULL DEFAULT '0',
  `sent` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `recv` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sum` DOUBLE(14, 6) NOT NULL DEFAULT '0.000000',
  `port_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `nas_id` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `ip` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sent2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `recv2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `acct_session_id` VARCHAR(32) NOT NULL DEFAULT '',
  `cid` VARCHAR(18) NOT NULL DEFAULT '',
  `bill_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `terminate_cause` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `framed_ipv6_prefix` VARBINARY(16) NOT NULL DEFAULT '',
  `acct_input_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `acct_output_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `ex_input_octets_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `ex_output_octets_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  KEY `uid` (`uid`, `start`)
)
  COMMENT = 'Internet sessions logs';

