SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS `mobile_categories` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL DEFAULT '',
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `mandatory` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `main_category` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Mobile categories';

CREATE TABLE IF NOT EXISTS `mobile_services` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(80) NOT NULL DEFAULT '',
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `user_description` VARCHAR(255) NOT NULL DEFAULT '',
  `price` DOUBLE(14, 2) UNSIGNED NOT NULL DEFAULT '0.00',
  `priority` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mandatory` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `filter_id` VARCHAR(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Mobile services';

CREATE TABLE IF NOT EXISTS `mobile_tariff_services` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tp_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `service_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Mobile tariff plans';

CREATE TABLE IF NOT EXISTS `mobile_main` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT(11) NOT NULL DEFAULT '0',
  `phone` VARCHAR(64) NOT NULL DEFAULT '',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `activate` DATE NOT NULL DEFAULT '0000-00-00',
  `disable` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `comments` VARCHAR(255) NOT NULL DEFAULT '',
  `transaction_id` VARCHAR(64) NOT NULL DEFAULT '',
  `tp_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `tp_disable` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `tp_activate` DATE NOT NULL DEFAULT '0000-00-00',
  `external_method` VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY (`phone`),
  KEY `uid` (`uid`),
  KEY `tp_id` (`tp_id`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Mobile user services';

CREATE TABLE IF NOT EXISTS `mobile_log` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uid` INT(11) NOT NULL DEFAULT 0,
  `transaction_id` VARCHAR(64) NOT NULL DEFAULT '',
  `external_method` VARCHAR(64) NOT NULL DEFAULT '',
  `user_subscribe_id` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `response` TEXT NOT NULL,
  `callback_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `callback` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_subscribe_id` (`user_subscribe_id`)
)
  COMMENT = 'Mobile log';