SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS `sms_log` (
  `uid` INT(10) UNSIGNED DEFAULT 0 NOT NULL,
  `message` CHAR(255) DEFAULT '' NOT NULL,
  `phone` CHAR(16) DEFAULT '' NOT NULL,
  `datetime` DATETIME NOT NULL,
  `status` TINYINT(3) UNSIGNED DEFAULT 0 NOT NULL,
  `ext_id` VARCHAR(20) DEFAULT '' NOT NULL,
  `status_date` DATETIME NOT NULL,
  `ext_status` VARCHAR(20) DEFAULT '' NOT NULL,
  `id` INT(10) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
  KEY `uid` (`uid`)
)
  ENGINE = InnoDB DEFAULT CHARSET = utf8 COMMENT = 'Sms log';

CREATE TABLE IF NOT EXISTS `sms_services` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `plugin` VARCHAR(32) NOT NULL DEFAULT '',
  `status` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  `comment` VARCHAR(250) DEFAULT '',
  `debug` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  `debug_file` VARCHAR(120) NOT NULL DEFAULT '',
  `by_default` TINYINT(1) UNSIGNED  NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `status` (`status`)
)
  DEFAULT CHARSET = utf8 COMMENT = 'Sms Services';

CREATE TABLE IF NOT EXISTS `sms_service_params`(
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `param` VARCHAR(50) NOT NULL DEFAULT '',
  `value` VARCHAR(400) NOT NULL DEFAULT '',
  `service_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY `id` (`id`),
  FOREIGN KEY (`service_id`) REFERENCES `sms_services` (`id`) ON DELETE CASCADE
)
  DEFAULT CHARSET = utf8 COMMENT = 'Sms service params';