ALTER TABLE `info_info` MODIFY COLUMN `comment_id` BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE `groups` MODIFY COLUMN `sms_service` INT(10) UNSIGNED NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS `sms_services` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `plugin` VARCHAR(32) NOT NULL DEFAULT '',
  `status` TINYINT(2) UNSIGNED NOT NULL DEFAULT '0',
  `comment` VARCHAR(250) DEFAULT '',
  `debug` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  `debug_file` VARCHAR(120) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `status` (`status`)
)
  DEFAULT CHARSET = 'utf8' COMMENT = 'Sms Services';

CREATE TABLE IF NOT EXISTS `sms_service_params`(
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `param` VARCHAR(50) NOT NULL DEFAULT '',
  `value` VARCHAR(400) NOT NULL DEFAULT '',
  `service_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY `id` (`id`),
  FOREIGN KEY (`service_id`) REFERENCES `sms_services` (`id`) ON DELETE CASCADE
)
  DEFAULT CHARSET = 'utf8' COMMENT = 'Sms service params';
ALTER TABLE `info_info` MODIFY COLUMN `comment_id` INT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `info_info` CHANGE COLUMN `admin_id` `aid` SMALLINT DEFAULT 0 NOT NULL;
ALTER TABLE `info_info` MODIFY COLUMN `document_id` SMALLINT(6) UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `info_comments` MODIFY COLUMN `id` INT UNSIGNED NOT NULL AUTO_INCREMENT;
ALTER TABLE `info_documents` MODIFY COLUMN `comment_id` INT UNSIGNED  DEFAULT 0 NOT NULL;
ALTER TABLE `info_change_comments` MODIFY COLUMN `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE `info_change_comments` MODIFY COLUMN `id_comments` INT UNSIGNED DEFAULT 0 NOT NULL;
ALTER TABLE `info_change_comments` MODIFY COLUMN `aid` SMALLINT(11) UNSIGNED DEFAULT 0 NOT NULL;