ALTER TABLE `tags` ADD COLUMN `expire_days` SMALLINT(3) UNSIGNED NOT NULL DEFAULT 0;

INSERT INTO `config` (`param`, `value`, `domain_id`) VALUES
  ('ORGANIZATION_PRIVACY_POLICY_URL_1', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_1', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_2', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_2', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_3', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_3', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_4', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_4', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_5', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_5', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_6', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_6', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_7', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_7', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_8', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_8', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_9', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_9', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_URL_10', '', 0),
  ('ORGANIZATION_PRIVACY_POLICY_DESCRIPTION_10', '', 0);
