ALTER TABLE `tasks_main` ADD COLUMN `parent_id` INT(10) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `tasks_main` ADD COLUMN `path` VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE `mobile_main` ADD COLUMN `comments` VARCHAR(255) NOT NULL DEFAULT '';
TRUNCATE TABLE `viber_tmp`;
ALTER TABLE `viber_tmp` DROP COLUMN `uid`;
ALTER TABLE `viber_tmp` ADD COLUMN `sender_id` VARCHAR(32) NOT NULL DEFAULT '';

TRUNCATE TABLE `telegram_tmp`;
ALTER TABLE `telegram_tmp` DROP COLUMN `uid`;
ALTER TABLE `telegram_tmp` ADD COLUMN `user_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0;
