ALTER TABLE `info_fields` ADD COLUMN `parent_id` TINYINT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `info_fields` ADD COLUMN `parent_value_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `fees_types` ADD COLUMN `parent_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0;