ALTER TABLE `discounts_main` ADD COLUMN `tp_id` SMALLINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `ring_users_filters` ADD COLUMN `phone` VARCHAR(16) NOT NULL DEFAULT 0;

ALTER TABLE `paysys_log` ADD COLUMN `recurrent_payment` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0';
