openapi: 3.0.3
info:
  title: ABillS ADMIN API
  version: 1.2.9
  description: >
    Last modified 2024-08-14 <br>
    Have other version of API? 
    Specification stored in billing folder. Location /usr/abills/misc/bundle_admin.yaml.
    Copy it and upload it to your favorite OPEN API viewer.
  contact:
    name: Have a question? Support contacts
    url: https://support.abills.net.ua/
    email: dev@abills.net.ua
  x-logo:
    url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDYlcnHnHZISgLa126i5ofPhroCS3CY3sac_6KCrs-kA&s
  x-providerName: abills.net.ua
externalDocs:
  description: Redocly
  url: https://demo.abills.net.ua:9443/redocly-admin.html
servers:
  - url: https://demo.abills.net.ua:9443/api.cgi
    description: Test Demo Server
tags:
  - name: admins
    description: Работа с администраторами
  - name: builds
    description: Дома
  - name: callback
    description: Работа с обратными вызовами
  - name: companies
    description: Компании пользователей
  - name: districts
    description: Районы
  - name: fees
    description: Списания
  - name: finance
    description: Получение курсов валют
  - name: global
    description: Унифицированные вызовы несколько путей в одном
  - name: groups
    description: Группы пользователей
  - name: intervals
    description: Интервалы тарифов
  - name: online
    description: Сессии пользователя
  - name: payments
    description: Оплаты
  - name: streets
    description: Улицы
  - name: tp
    description: Тарифные планы
  - name: users
    description: Работа с пользователями
  - name: version
    description: Версии
  - name: abon
    description: Abon
  - name: cablecat
    description: Работа с модулем Cablecat
  - name: crm
    description: Crm
  - name: docs
    description: Работа с обратными документами
  - name: equipment
    description: Работа с оборудованием (модуль Equipment)
  - name: internet
    description: Internet
  - name: iptv
    description: Iptv
  - name: maps
    description: Работа с модулем Maps
  - name: msgs
    description: Msgs
  - name: portal
    description: Новостной веб-портал
  - name: storage
    description: Работа с модулем Storage
  - name: tags
    description: Работа с метками пользователя (модуль Tags)
  - name: ureports
    description: Работа с оповещениями (модуль Ureports)
  - name: voip
    description: Работа с телефонией (модуль Voip)
paths:
  $ref: "./admin/admins/paths.yaml"
  $ref: "./admin/builds/paths.yaml"
  $ref: "./admin/callback/paths.yaml"
  $ref: "./admin/companies/paths.yaml"
  $ref: "./admin/districts/paths.yaml"
  $ref: "./admin/fees/paths.yaml"
  $ref: "./admin/finance/paths.yaml"
  $ref: "./admin/global/paths.yaml"
  $ref: "./admin/groups/paths.yaml"
  $ref: "./admin/intervals/paths.yaml"
  $ref: "./admin/online/paths.yaml"
  $ref: "./admin/payments/paths.yaml"
  $ref: "./admin/streets/paths.yaml"
  $ref: "./admin/tp/paths.yaml"
  $ref: "./admin/users/paths.yaml"
  $ref: "./admin/version/paths.yaml"
  $ref: "../../Abills/modules/Abon/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Cablecat/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Crm/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Docs/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Equipment/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Internet/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Iptv/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Maps/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Msgs/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Portal/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Storage/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Tags/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Ureports/Api/swagger/admin/paths.yaml"
  $ref: "../../Abills/modules/Voip/Api/swagger/admin/paths.yaml"
components:
  schemas:
    ApiGetResponse400:
      type: object
      properties:
        errno:
          type: integer
          example: 2
        errstr:
          type: string
          example: ERROR_NOT_EXIST
    ApiAddResponse200:
      type: object
      properties:
        total:
          type: integer
          example: 0
        affected:
          type: integer
          example: 1
        insertId:
          type: integer
          example: 37
    ApiAddResponse400:
      type: object
      properties:
        affected:
          type: number
          example: 0
        total:
          type: number
          example: 0
        errno:
          type: number
          example: 7
        errstr:
          type: string
          example: ERROR_DUPLICATE
    ApiChangeResponse200:
      type: object
      properties:
        affected:
          type: integer
          format: int32
          example: 1
        total:
          type: integer
          format: int32
          example: 0
    ApiDeleteResponse200:
      type: object
      properties:
        total:
          type: integer
          example: 1
        affected:
          type: integer
          example: 1
    ApiDeleteResponse400:
      type: object
      properties:
        total:
          type: integer
          example: 0
        affected:
          type: integer
          example: 0
    OnlineSessionsArray:
      type: array
      items:
        $ref: "#/components/schemas/OnlineSession"
    OnlineSession:
      type: object
      properties:
        clientIpNum:
          type: integer
          example: 3232238092
        nasId:
          type: integer
          example: 12
        nasPortId:
          type: integer
          example: 12
        duration:
          type: string
          example: 838:59:59
        status:
          type: integer
          example: 10
        userName:
          type: string
          example: userName
        clientIp:
          type: string
          example: 192.168.10.12
        acctSessionId:
          type: string
          example: Akie6VpiYU
        guest:
          type: number
          example: 0
        uid:
          type: number
          example: 101
  securitySchemes:
    KEY:
      type: apiKey
      name: KEY
      in: header
