$lang{STREAMS_COUNT} = 'Streams count';
$lang{TARIF_PLAN} = 'Tariff plan';
$lang{TARIF_PLANS} = 'Tariff plans';
$lang{CAMERAS} = 'Cameras';
$lang{SUBSCRIBE} = 'Subscribe';
$lang{UNSUBSCRIBE} = 'Unsubscribe';
$lang{YOU_HAVE_BEEN_SUCCESSFULY_UNSUBSCRIBED} = 'You have been successfuly unsubscribed';
$lang{YOU_HAVE_REGISTERED_MAX_ALLOWED_STREAMS_COUNT} = 'You have registered max allowed count of streams for tariff plan';

$lang{ORIENTATION} = 'Orientation';
$lang{NORMAL} = 'Normal';
$lang{ROTATE} = 'Rotate';
$lang{RIGHT} = 'right';
$lang{LEFT} = 'left';
$lang{INVERTED} = 'Inverted';
$lang{FLIPPED} = 'Flipped';
$lang{HORIZONTALLY} = 'Horizontally';
$lang{VERTICALLY} = 'Vertically';
$lang{CAMERA} = 'Camera';

$lang{HOME_CAM} = 'Home camera';
$lang{PUBLIC_CAM} = 'Public camera';
$lang{PRIVATE_CAM} = 'Private camera';
$lang{NO_TARIFF_PLAN_SELECTED} = "No tariff plan selected";
$lang{CAM_TITLE} = "Title";
$lang{ONLY_LATIN_LETTER} = "Name can only consist of latin letters, digits and '_'. Ex. some_name";
$lang{NOT_CORRECT_HOST} = "Not correct Rtsp host. (10.0.0.1)";
$lang{URL_FOR_SCREENSHOTS} = "URL for screenshots";
$lang{OWNER} = "Owner (Login)";
$lang{TP_CAMERAS} = "Cameras Subscribes";
$lang{EXCEEDED_THE_NUMBER} = "You have exceeded the number of cameras";
$lang{NUMBER_OF_GROUPS} = "Number of cameras in the group exceeded";
$lang{NUMBER_OF_USERS} = "Number of users in the group exceeded";
$lang{CAMS_ARCHIVE} = "Archive";
$lang{CAM} = "Camera";
$lang{LOCATION_CAMS} = 'Location';
$lang{CAM_TITLE} = 'Group';
$lang{CONSTANTLY_WORKING} = 'Constantly working';
$lang{PRE_IMAGE} = 'Preview image';
$lang{LIMIT_ARCHIVE} = 'Restrict access to the archive';
$lang{ONLY_VIDEO} = 'Video Only';
$lang{TYPE_FOR_SERVICE} = 'Type for service';

1;