#!perl
=head1 NAME

  Internet module

  Internet Dialup/VPN/IPoE functions

  Error ID: 9xx

=cut


use strict;
use warnings FATAL => 'all';
use Abills::Defs;
use Abills::Base qw(date_diff in_array sendmail sec2time show_log mk_unique_value int2byte _bp int2ip ip2int days_in_month clearquotes next_month);
use Abills::Filters qw(_mac_former human_exp);
use Internet;
use Internet::Sessions;
use Finance;
use Fees;
use Shedule;
use Tariffs;
use Nas;
use Log;

our ($db,
  %conf,
  $admin,
  %permissions,
  $ui,
  @WEEKDAYS,
  @MONTHES,
  %err_strs,
  %lang,
  $PG,
  $users,
  @PERIODS, # ???
  %ADMIN_REPORT
);

our Abills::HTML $html;

my $Internet = Internet->new($db, $admin, \%conf);
my $Shedule  = Shedule->new($db, $admin, \%conf);
my $Payments = Finance->payments($db, $admin, \%conf);
my $Tariffs  = Tariffs->new($db, \%conf, $admin);
my $Nas      = Nas->new($db, \%conf, $admin);
my $Log      = Log->new($db, \%conf);

require Control::Services;
require Internet::User_portal;
require Internet::Quick_reports;

if($permissions{3}) {
  require Internet::Reports;
}

if($permissions{4}) {
  require Internet::Configure;
}

if($permissions{5}) {
  require Internet::Monitoring;
}

#if($FORM{UID}) {
  require Internet::Users;
#}

if(%ADMIN_REPORT) {
  require Internet::Periodic;
  require Internet::Ipoe_periodic;
}

#**********************************************************
=head2 internet_users_search($Internet_)

=cut
#**********************************************************
sub internet_users_search {
  my ($Internet_) = @_;

  $index=get_function_index('internet_users_list') if ( $functions{$index} && $functions{$index} ne 'internet_users_list' );
  $Internet->{GROUP_SEL}  = sel_groups();
  $Internet->{STATUS_SEL} = sel_status({
    STATUS => $FORM{INTERNET_STATUS} || '',
    ALL    => 1,
    NAME   => 'INTERNET_STATUS'
  });

  if ($conf{INTERNET_LOGIN}) {
    $Internet_->{INTERNET_LOGIN_FORM} .= $html->tpl_show(templates('form_row'), { ID => 'INTERNET_LOGIN',
        NAME  => "Internet $lang{LOGIN}",
        VALUE => $html->form_input('INTERNET_LOGIN', $FORM{INTERNET_LOGIN} || '%INTERNET_LOGIN%', { ID => 'INTERNET_LOGIN' })
      }, { OUTPUT2RETURN => 1 });
  }

  $Internet_->{TP_SEL} = sel_tp({
    MODULE => 'Dv;Internet',
    SELECT    => 'TP_ID',
    EX_PARAMS => 'multiple="multiple"'
  });

  $Internet_->{NAS_SEL}=$html->form_select(
    'NAS_ID',
    {
      SELECTED          => $Internet->{NAS_ID} || $FORM{NAS_ID},
      SEL_LIST          => '',
      #$Nas->list({ COLS_NAME => 1, DOMAIN_ID => $users->{DOMAIN_ID}, SHORT => 1, NAS_NAME => '_SHOW' }),
      SEL_KEY           => 'nas_id',
      SEL_VALUE         => 'nas_name',
      SEL_OPTIONS       => { '' => '' },
      MAIN_MENU         => get_function_index( 'form_nas' ),
      MAIN_MENU_ARGV    => ($Internet->{NAS_ID}) ? "NAS_ID=$Internet->{NAS_ID}" : '',
      EXT_BUTTON        => $Internet->{SWITCH_STATUS},
      # Popup window
      POPUP_WINDOW      => 'form_search_nas',
      POPUP_WINDOW_TYPE => 'search',
      SEARCH_STRING     => 'POPUP=1&NAS_SEARCH=0'. (($FORM{UID}) ? "&UID=$FORM{UID}" : ''),
      HAS_NAME          => 1,
      TOOLTIP           => 'nas_name'
    }
  );

  my $ip_pool_list = $Nas->ip_pools_list({ STATIC => 1, COLS_NAME => 1 });

  if($FORM{IP_POOL}) {
    foreach my $line (@$ip_pool_list) {
      if($FORM{IP_POOL} == $line->{id}) {
        $FORM{IP}='>=' . int2ip($line->{ip}) . ';<=' . int2ip($line->{last_ip_num});
      }
    }
  }

  $Internet_->{IP_POOL_SEL} = $html->form_select(
    'IP_POOL',
    {
      SELECTED    => $FORM{IP_POOL},
      SEL_LIST    => $ip_pool_list,
      NO_ID       => 1,
      SEL_OPTIONS => { '' => '' },
    }
  );

  $Internet_->{REGISTRATION_RANGE} = $html->form_daterangepicker({
    NAME         => 'REGISTRATION_FROM/REGISTRATION_TO',
    VALUE        => $FORM{'REGISTRATION_FROM_REGISTRATION_TO'},
    RETURN_INPUT => 1
  });

  $Internet_->{DISABLE_SELECT} = $html->form_select(
    'DISABLE',
    {
      SELECTED => $FORM{DISABLE},
      SEL_HASH => {
        ('' => ''),
        (0 => $lang{ACTIV}),
        (1 => $lang{DISABLE}),
      },
      NO_ID    => 1
    });


  $Internet_->{DELETE_SELECT} = $html->form_select(
    'DELETED',
    {
      SELECTED => $FORM{DELETED},
      SEL_HASH => {
        ('' => ''),
        (0 => $lang{NO}),
        (1 => $lang{YES})
      },
      NO_ID    => 1
    });

  my $search_form = $html->tpl_show(_include('internet_users_search', 'Internet'), { %$Internet_, %FORM }, { OUTPUT2RETURN => 1 });
  $search_form .= $html->tpl_show(templates('form_search_personal_info'), { %$Internet_, %FORM }, { OUTPUT2RETURN => 1 });
  $search_form .= $html->tpl_show(templates('form_search_users'), { %$Internet_, %FORM }, { OUTPUT2RETURN => 1 });

  form_search({
    SEARCH_FORM  => $search_form,
    ADDRESS_FORM  => 1,
    CONTROL_FORM  => 1
  });

  return 1;
}

#**********************************************************
=head2 internet_multiuser($ids) - Make multiuser panel

  Arguments:
        $ids = string of ids

=cut
#**********************************************************
sub internet_multiuser {
  my ($ids) = @_;

  my @multiuser_arr = split(/, /, $ids || q{});
  my @multiuser_no_error;
  my %params;
  $Internet->list({
    GROUP_BY  => 'internet.id',
    ID        => join(';', @multiuser_arr),
    LIST2HASH => 'id,uid',
    PAGE_ROWS => 99999,
  });
  my $uid_hash = $Internet->{list_hash};

  if ($FORM{MU_TP} && $FORM{TP_SHEDULE} eq '0000-00-00') {
    $params{TP_ID} = $FORM{INTERNET_MU_TP};
  }
  if ($FORM{MU_DATE}) {
    $params{SERVICE_EXPIRE} = $FORM{INTERNET_MU_DATEPICKER};
  }
  if ($FORM{MU_STATUS}) {
    $params{STATUS} = $FORM{INTERNET_MU_STATUS};
  }
  if ($FORM{MU_REDUCTION}) {
    $params{REDUCTION} = $FORM{MU_REDUCTION_SUM} || 0;
    $params{REDUCTION_DATE} = $FORM{MU_REDUCTION_DATE} || '0000-00-00';
  }
  if ($FORM{MU_ACTIVATE}) {
    $params{ACTIVATE} = $FORM{MU_ACTIVATE_DATE};
  }

  if ($#multiuser_arr < 0) {
    $html->message('err', $lang{MULTIUSER_OP}, "$lang{SELECT_USER}");
    return 1;
  }
  elsif ($FORM{MU_TP} && $FORM{TP_SHEDULE} ne '0000-00-00') {
    my ($year, $month, $day) = split(/-/, $FORM{TP_SHEDULE}, 3);
    foreach my $id (@multiuser_arr) {
      $Internet->info($uid_hash->{$id}, { ID => $id });
      $Shedule->add(
        {
          UID          => $uid_hash->{$id},
          TYPE         => 'tp',
          ACTION       => "$id:$FORM{INTERNET_MU_TP}",
          D            => $day,
          M            => $month,
          Y            => $year,
          MODULE       => 'Internet',
          COMMENTS     => "$lang{FROM}: $Internet->{TP_ID}:". ($Internet->{TP_NAME} || ""),
          ADMIN_ACTION => 1
        }
      );

      if ( _error_show($Shedule) ) {
        last;
      }
      push @multiuser_no_error, $id;
    }
    $html->message('info', $lang{MULTIUSER_OP}, "$lang{TO_PLAN}\n$lang{SERVICE}: " . join(', ', @multiuser_no_error) );
  }
  elsif ($FORM{MU_CREDIT} || $FORM{MU_REDUCTION} || $FORM{MU_ACTIVATE}) {
    $params{CREDIT} = $FORM{MU_CREDIT_SUM} || 0;
    $params{CREDIT_DATE} = $FORM{MU_CREDIT_DATE} || '0000-00-00';

    my %uids_hash = reverse %$uid_hash;
    foreach my $uid (keys %uids_hash) {
      $users->change( $uid,
        {
          UID    => $uid,
          %params
        }
      );
    }
  }
  elsif ($FORM{MU_SET_IPV6}) {
    my $Ip_pool  = $Nas->ip_pools_info($FORM{INTERNET_MU_IPV6_POLL});
    foreach my $id (@multiuser_arr) {
      my $uid_hex = sprintf("%x", $uid_hash->{$id});
      my $id_hex  = sprintf("%x", $id);
      my $ipv6    = $Ip_pool->{IPV6_TEMPLATE} || '';
      $ipv6       =~ s/\{UID\}/$uid_hex/g;
      $ipv6       =~ s/\{ID\}/$id_hex/g;
      my $ipv6_pd = $Ip_pool->{IPV6_PD_TEMPLATE} || '';
      $ipv6_pd    =~ s/\{UID\}/$uid_hex/g;
      $ipv6_pd    =~ s/\{ID\}/$id_hex/g;

      $Internet->change({
        ID               => $id,
        UID              => $uid_hash->{$id},
        IPV6             => $ipv6,
        IPV6_PREFIX      => $ipv6_pd,
        IPV6_MASK        => $Ip_pool->{IPV6_MASK},
        IPV6_PREFIX_MASK => $Ip_pool->{IPV6_PD_MASK},
      });
    }
  }
  elsif ($FORM{MU_SET_IPV4}) {
    require Internet::User_ips;
    my $Ip_pool  = $Nas->ip_pools_info($FORM{INTERNET_MU_IPV4_POLL});

    foreach my $id (@multiuser_arr) {
      $Internet->change({
        ID  => $id,
        UID => $uid_hash->{$id},
        IP  => get_static_ip($FORM{INTERNET_MU_IPV4_POLL}),
      });
    }
  }
  elsif (defined($FORM{MU_TAGS_USER} && in_array('Tags', \@MODULES))) {
    require Tags;

    my $Tags = Tags->new($db, $admin, \%conf);

    foreach my $id (@multiuser_arr) {
      $Tags->tags_user_change({
        IDS => $FORM{TAGS},
        UID => $uid_hash->{$id},
      });
      $html->message('err', $lang{INFO}, "$lang{TAGS} $lang{NOT} $lang{ADDED} UID:$id") if ($Tags->{errno});
    }
  }
  elsif (!%params) {
    $html->message('warn', $lang{MULTIUSER_OP}, "$lang{THERE_ARE_NO_SETTINGS_TO_CHANGE}");
    return 1;
  }
  else {
    foreach my $id (@multiuser_arr) {
      $Internet->change(
        {
          ID  => $id,
          UID => $uid_hash->{$id},
          %params
        }
      );

      if ( _error_show($Internet, { MODULE_NAME => $lang{INTERNET} }) ) {
        last;
      }
      push @multiuser_no_error, $id;
    }

    $html->message('info', $lang{MULTIUSER_OP}, "$lang{CHANGED}\n$lang{SERVICE}: " . join(', ', @multiuser_no_error) );
  }

  return 1;
}

#**********************************************************
=head2 internet_users_list($attr)

=cut
#**********************************************************
sub internet_users_list {
  my ($attr) = @_;

  if (!$permissions{0}{2}) {
    return 0;
  }

  if($FORM{import}){
    if (!$permissions{0}{17}) {
      $html->message('err', $lang{ERROR}, "$lang{IMPORT} $lang{ERR_ACCESS_DENY}");
      return 0;
    }

    if ($FORM{add}) {
      my $import_accounts = import_former(\%FORM);
      my $total = $#{$import_accounts} + 1;
      my $main_id = 'UID';

      if (!$import_accounts->[0]->{UID}) {
        if ($import_accounts->[0]->{INTERNET_LOGIN}) {
          $main_id = 'INTERNET_LOGIN';
        }
        elsif ($import_accounts->[0]->{MAIN_ID}) {
          $main_id = $import_accounts->[0]->{MAIN_ID};
        }
      }

      foreach my $_user (@$import_accounts) {
        my $list = $Internet->list({
          LOGIN     => '_SHOW',
          $main_id  => $_user->{$main_id},
          COLS_NAME => 1
        });

        if ($Internet->{TOTAL} > 0) {

          my $uid = $list->[0]->{uid};
          $Internet->change({ %$_user, UID => $uid });
          print $html->button($list->[0]->{login}, "index=15&UID=$uid") . " ($uid)' Ok" . $html->br();

        } else {
          $Internet->add({ %$_user });
          if ($Internet->{errno}) {
            _error_show($users);
          }
        }
      }

      $html->message('info', $lang{INFO}, "$lang{ADDED}\n $lang{FILE}: $FORM{UPLOAD_FILE}{filename}\n Size: $FORM{UPLOAD_FILE}{Size}\n Count: $total");

      return 1;
    }

    my $import_fields = $html->form_select('IMPORT_FIELDS',
      {
        SELECTED  => $FORM{IMPORT_FIELDS},
        SEL_ARRAY => [
          'UID',
          'TP_ID',
          'STATUS'
        ],
        EX_PARAMS => 'multiple="multiple"'
      });

    my $encode = $html->form_select(
      'ENCODE',
      {
        SELECTED  => $FORM{ENCODE},
        SEL_ARRAY => [ '', 'win2utf8', 'utf82win', 'win2koi', 'koi2win', 'win2iso', 'iso2win', 'win2dos', 'dos2win' ],
      }
    );

    my $extra_row = $html->tpl_show(templates('form_row'), {
      ID    => 'ENCODE',
      NAME  => $lang{ENCODE},
      VALUE => $encode },
      { OUTPUT2RETURN => 1 });

    $html->tpl_show(templates('form_import'), {
      IMPORT_FIELDS     => 'UID,TP_ID,STATUS',
      CALLBACK_FUNC     => 'internet_users_list',
      IMPORT_FIELDS_SEL => $import_fields,
      EXTRA_ROWS        => $extra_row
    });

    return 1;
  }

  if ($FORM{GLOBAL}) {
    #$Internet->{GLOBAL} = 1;
    $FORM{UNIVERSAL_SEARCH} = 1;
  }

  if($FORM{INTERNET_MULTIUSER} && $FORM{IDS}) {
    internet_multiuser($FORM{IDS});
  }

  if (defined($FORM{TP_NUM}) && $FORM{TP_NUM} eq '0') {
    $FORM{TP_ID} = '0';
  }
  else {
    if ($attr->{TP}) {
      if ($FORM{TP_NUM}) {
        $FORM{TP_ID} = $FORM{TP_NUM};
        $FORM{TP_ID} =~ s/,/;/g;
      }

      $LIST_PARAMS{TP_ID} = $FORM{TP_NUM} || $FORM{TP_ID};
    }
    elsif ($FORM{TP_ID} || $FORM{TP_NUM}) {
      if(defined(&internet_tp)) {
        $FORM{TP_ID} = $FORM{TP_NUM} if ($FORM{TP_NUM});
        $FORM{subf} = $index;
        internet_tp();
        return 0;
      }
      #$LIST_PARAMS{TP_ID}=$FORM{TP_ID};
    }
  }

  internet_users_search($Internet);
  if($LIST_PARAMS{TP_ID} && $LIST_PARAMS{TP_ID} =~ /,/) {
    $LIST_PARAMS{TP_ID} =~ s/,\s?/;/g;
  }

  # To prevent duplicating INTERNET_STATUS field in URL, should cut it from original $qs
  my $clear_qs = $pages_qs || q{};
  $clear_qs =~ s/\&INTERNET_STATUS=\d+//;

  my $current_status = (defined $FORM{INTERNET_STATUS} && $FORM{INTERNET_STATUS} =~ /^\d+$/)
                         ? $FORM{INTERNET_STATUS}
                         : undef;
  my $status_bar     = $html->button($lang{ALL}, "index=$index$clear_qs", {
      class => "btn btn-secondary " . (!defined $FORM{INTERNET_STATUS} ? 'active' : '' )
    });

  my $service_status = sel_status({ HASH_RESULT => 1 });
  foreach my $i (sort keys %$service_status) {
    my $active         = '';
    my ($name) = split(/:/, $service_status->{$i}, 2);

    if (defined $current_status && $current_status == $i) {
      $LIST_PARAMS{INTERNET_STATUS} = $FORM{INTERNET_STATUS};
      $pages_qs .= "&INTERNET_STATUS=$i";
      $active    = 'active';
    }

    $status_bar .= $html->button($name, "index=$index&INTERNET_STATUS=$i$clear_qs", { class => "btn btn-secondary $active"  });
  }

  ##print $html->letters_list({ pages_qs => $pages_qs });
  #  if ($FORM{letter}) {
  #    $LIST_PARAMS{LOGIN} = "$FORM{letter}*";
  #    $pages_qs .= "&letter=$FORM{letter}";
  #  }

  if ($FORM{SERVICES} && $FORM{SERVICES} =~ m/^[<>]?\d+$/) {
    my $search = $FORM{SERVICES};
    if ($search !~ m/^[<>]/) {
      $search = "=$search";
    }
    $LIST_PARAMS{SERVICE_COUNT}=$FORM{SERVICES};
    $LIST_PARAMS{GROUP_BY}="u.uid HAVING service_count $search";
  }
  else {
    $LIST_PARAMS{GROUP_BY}=' internet.id';
  }

  my $reg_index = get_function_index('form_wizard');
  my Abills::HTML $table;
  my $list;

  my %EXT_PARAM_FORMER = ();
  if (in_array('Maps2', \@MODULES)) {
    $EXT_PARAM_FORMER{MAP} = 1;
    $EXT_PARAM_FORMER{MAP_FIELDS} = 'ADDRESS_FLAT,LOGIN,DEPOSIT,FIO,TP_NAME,ONLINE';
  }

  $LIST_PARAMS{GID} = $FORM{GID} if $FORM{GID};

  ($table, $list) = result_former({
    INPUT_DATA      => $Internet,
    FUNCTION        => 'list',
    BASE_FIELDS     => 0,
    DEFAULT_FIELDS  => 'LOGIN,FIO,DEPOSIT,CREDIT,TP_NAME,INTERNET_STATUS,ID, TP_ID',
    HIDDEN_FIELDS   => 'PRIORITY',
    APPEND_FIELDS   =>  'UID',
    FUNCTION_FIELDS => 'form_payments,internet_stats',
    %EXT_PARAM_FORMER,
    MAP_FILTERS     => { id => 'search_link:form_users:UID'
      #online => ''
    },
    MULTISELECT     => ($permissions{0}{7}) ? 'IDS:id:internet_users_list' : '',
    EXT_TITLES      => {
      'ip_num'                => 'IP',
      'netmask'               => 'NETMASK',
      'speed'                 => $lang{SPEED},
      'port'                  => $lang{PORT},
      'cid'                   => 'CID',
      'filter_id'             => 'Filter ID',
      'tp_name'               => $lang{TARIF_PLAN},
      'tp_id'                 => "$lang{TARIF_PLAN} ID",
      'internet_status'       => "Internet $lang{STATUS}",
      'internet_status_date'  => "$lang{STATUS} $lang{DATE}",
      'internet_comments'     => "Internet $lang{COMMENTS}",
      'online'                => 'Online',
      'online_ip'             => 'Online IP',
      'online_cid'            => 'Online CID',
      'online_duration'       => 'Online ' . $lang{DURATION},
      'month_fee'             => $lang{MONTH_FEE},
      'day_fee'               => $lang{DAY_FEE},
      'internet_expire'       => "Internet $lang{EXPIRE}",
      'internet_login'        => "Internet $lang{LOGIN}",
      'internet_password'     => "Internet $lang{PASSWD}",
      'month_traffic_in'      => "$lang{MONTH} $lang{RECV}",
      'month_traffic_out'     => "$lang{MONTH} $lang{SENT}",
      'month_ipn_traffic_in'  => "$lang{MONTH} IPN $lang{RECV}",
      'month_ipn_traffic_out' => "$lang{MONTH} IPN $lang{SENT}",
      'personal_tp'           => "$lang{PERSONAL} $lang{TARIF_PLAN}",
      'shedule'               => $lang{SHEDULE},
      'cpe_mac'               => "CPE MAC",
      'nas_id'                => 'NAS_ID',
      'id'                    => $lang{ID_TP_SEARCH},
      'ipv6'                  => 'IPv6 Address',
      'ipv6_prefix'           => 'IPv6 Prefix'
    },
    SELECT_VALUE => {
      internet_status => $service_status,
      login_status    => $service_status
    },
    FILTER_COLS => {
      ip_num                => 'int2ip',
      month_traffic_in      => 'int2byte',
      month_traffic_out     => 'int2byte',
      month_ipn_traffic_in  => 'int2byte',
      month_ipn_traffic_out => 'int2byte',
    },
    TABLE => {
      width      => '100%',
      caption    => "$lang{INTERNET} - $lang{USERS}",
      qs         => $pages_qs,
      ID         => 'INTERNET_USERS_LIST',
      header     => $status_bar,
      EXPORT     => 1,
      MENU       => "$lang{ADD}:index=" . $reg_index . ':add' . ";$lang{SEARCH}:index=$index&search_form=1:search",
      IMPORT           => "$SELF_URL?get_index=internet_users_list&header=2&import=1",
    },
    MAKE_ROWS     => 1,
    SEARCH_FORMER => 1,
    MODULE        => 'Internet',
    TOTAL         => 1,
    SHOW_MORE_THEN=> 1,
    OUTPUT2RETURN => 1
  });

  if ( _error_show($Internet, { MODULE_NAME => $lang{INTERNET} }) ) {
    return 0;
  }
  elsif($Internet->{TOTAL} == 1 && $FORM{SKIP_FULL_INFO}){
    print $table->show();
    return 1;
  }
  elsif ($Internet->{TOTAL} == 1) {
    delete $FORM{LOGIN};
    $ui = user_info($list->[0]->{uid});

    if ($ui) {
      print $ui->{TABLE_SHOW};
      form_users({ USER_INFO => $ui });
      return 1;
    }
  }
  elsif (! $Internet->{TOTAL}) {
    $html->message('err', $lang{ERROR}, "$lang{USER} $lang{NOT_EXIST}");
    return 0;
  }

  if( $FORM{EXPORT_CONTENT} ) {
    print $table;
  }
  elsif ( $Internet->{TOTAL} > 1) {
    if ($permissions{0}{7}) {
      $html->{FORM_ID} = 'internet_users_list';
      $Internet->{MU_TP_SELECT} = $html->tpl_show(_include('internet_tp_shedule', 'Internet'), {
        TP_SEL   => sel_tp({ MODULE => 'Internet;Dv', SELECT => 'INTERNET_MU_TP' }),
        DATE_SEL => $html->form_datepicker('TP_SHEDULE', '0000-00-00')
      }, { OUTPUT2RETURN => 1 });
      $Internet->{MU_CREDIT_DATEPICKER} = $html->form_datepicker('MU_CREDIT_DATE', '0000-00-00');
      $Internet->{MU_TP_CHECKBOX} = $html->form_input('MU_TP', 1, { TYPE => 'checkbox', });
      $Internet->{MU_STATUS_CHECKBOX} = $html->form_input('MU_STATUS', 1, { TYPE => 'checkbox', });
      $Internet->{MU_STATUS_SELECT} = sel_status({ NAME => 'INTERNET_MU_STATUS' });
      $Internet->{MU_DATE} = $html->form_datepicker('INTERNET_MU_DATEPICKER', '0000-00-00');
      $Internet->{MU_DATE_CHECKBOX} = $html->form_input('MU_DATE', 1, { TYPE => 'checkbox', });
      $Internet->{IPV6_HIDE} = "style='display: none;'" unless ($conf{IPV6});

      if (in_array('Tags', \@MODULES)) {
        load_module('Tags', $html);
        $Internet->{MU_USER_TAGS} = tags_sel();
      }
      else {
        $Internet->{VISIBLE} = 'display: none;';
      }

      my $pool_ipv6_list = $Nas->ip_pools_list({
        IPV6      => 1,
        STATIC    => 1,
        NETMASK   => '_SHOW',
        COLS_NAME => 1
      });
      $Internet->{MU_IPV6_POLL_SEL} = $html->form_select('INTERNET_MU_IPV6_POLL', {
        SEL_LIST    => $pool_ipv6_list,
        NO_ID    => 1
      });
      my $pool_ipv4_list = $Nas->ip_pools_list({
        STATIC    => 1,
        NETMASK   => '_SHOW',
        COLS_NAME => 1
      });
      $Internet->{MU_IPV4_POLL_SEL} = $html->form_select('INTERNET_MU_IPV4_POLL', {
        SEL_LIST    => $pool_ipv4_list,
        NO_ID    => 1
      });
      print $html->form_main(
        {
          CONTENT => $table . $html->tpl_show(_include('internet_user_multiselect', 'Internet'), $Internet, { OUTPUT2RETURN => 1 }),
          HIDDEN  => {
            index              => get_function_index('internet_users_list'),
            INTERNET_MULTIUSER => 1
          },
          NAME    => $html->{FORM_ID},
          class   => 'hidden-print',
          ID      => $html->{FORM_ID},
        }
      );
    }
    else {
      print $html->form_main(
        {
          CONTENT => $table,
          HIDDEN  => {
            index => get_function_index('internet_users_list'),
          },
          NAME    => 'internet_users_list',
          class   => 'hidden-print',
          ID      => 'internet_users_list',
        }
      );
    }
  }

  return 1;
}

#**********************************************************
=head2 internet_error_user($attr)

=cut
#**********************************************************
sub internet_error_user {
  my ($attr) = @_;

  $attr->{USER_FORM}=1;

  if (!$permissions{0}{33}) {
    $html->message('warn', $lang{WARNING}, $lang{ERR_ACCESS_DENY});
    return 1;
  }

  return internet_error($attr);
}

#**********************************************************
=head2 internet_error($attr)

  Arguments:
    $attr
      USER_FORM

=cut
#**********************************************************
sub internet_error {
  my ($attr)    = @_;

  if (!$attr->{USER_FORM} && !$permissions{3}{6}) {
    $html->message('warn', $lang{WARNING}, $lang{ERR_ACCESS_DENY});
    return 1;
  }

  if($FORM{ID}) {
    print user_service_menu({
      SERVICE_FUNC_INDEX => get_function_index('internet_user'),
      PAGES_QS           => "&ID=$FORM{ID}",
      UID                => $FORM{UID},
      MK_MAIN            => 1
    });
  }

  my %log_levels_rev = reverse %Log::log_levels;
  my @ACTIONS = ('', 'AUTH', 'ACCT', 'HANGUP', 'CALCULATION', 'CMD', 'LOST_ALIVE', 'GUEST_MODE', 'DUB_IP');

  if ($attr->{USER_INFO}) {
    my $user = $attr->{USER_INFO};
    $LIST_PARAMS{LOGIN} = $user->{LOGIN};

    if ($conf{INTERNET_LOGIN}) {
      $Internet->info($user->{UID});
      if ($Internet->{INTERNET_LOGIN}) {
        $LIST_PARAMS{LOGIN}.=";$Internet->{INTERNET_LOGIN}";
      }
    }
  }
  elsif ($FORM{LOGIN}) {
    $LIST_PARAMS{LOGIN} = $FORM{LOGIN};
    $pages_qs .= "&LOGIN=$FORM{LOGIN}";
  }
  elsif ($FORM{UID}) {
    internet_user();
    return 1;
  }

  #Sql Part
  my %nas_ids = (
    '' => '',
    0  => 'UNKNOWN',
  );

  my $list = $Nas->list({
    PAGE_ROWS => 60000,
    NAS_ID    => '_SHOW',
    NAS_NAME  => '_SHOW',
    DESCR     => '_SHOW',
    MAC       => '_SHOW',
    COLS_NAME => 1,
  });

  my %nas_ids_sel = ();
  foreach my $line (@$list) {
    $line->{nas_name} //= q{};
    $nas_ids_sel{ $line->{id} }  = $line->{nas_name} ."/". ($line->{descr} || q{});
    $nas_ids{ $line->{id} }  = "$line->{nas_name}/". ($line->{descr} || q{});
    $nas_ids{ $line->{mac} } = "$line->{nas_name}/". ($line->{descr} || q{});
  }

  if($FORM{search_form}) {
    $Internet->{LOG_TYPE_SEL} = $html->form_select(
      'LOG_TYPE',
      {
        SELECTED => $FORM{LOG_TYPE},
        SEL_HASH => { '' => '', %log_levels_rev },
        NO_ID    => 1
      }
    );

    $Internet->{NAS_ID_SEL} = $html->form_select('NAS_ID', {
      SELECTED    => $FORM{NAS_ID} || q{},
      SEL_HASH    => \%nas_ids_sel,
      SEL_OPTIONS => { '' => $lang{ALL} },
    });

    $Internet->{ACTIONS_SEL} = $html->form_select(
      'ACTION',
      {
        SELECTED  => $FORM{ACTION},
        SEL_ARRAY => \@ACTIONS,
      }
    );

    form_search({ SEARCH_FORM => $html->tpl_show(_include('internet_errors_search', 'Internet'), { %FORM, %$Internet }, { OUTPUT2RETURN => 1 }) });
  }
  if (!$FORM{sort}) {
    $LIST_PARAMS{SORT} = 1;
    $LIST_PARAMS{DESC} = 'DESC';
  }

  $list = $Log->log_list({
    %LIST_PARAMS,
    ACTION    => $FORM{ACTION} || '_SHOW',
    TEXT      => $FORM{TEXT} || '',
    COLS_NAME => 1
  });

  my $table = $html->table({
    caption    => $lang{TOTAL},
    width      => '100%',
  });

  my $total = 0;
  foreach my $line (@{ $Log->{list} }) {
    $table->addrow($log_levels_rev{ $line->{log_type} },
      $html->button($line->{count}, "index=". get_function_index('internet_error') . "&LOG_TYPE=$line->{log_type}"));
    $total += $line->{count};
  }

  $table->addrow($lang{TOTAL}, $total);

  print $table->show();

  if(defined $FORM{LOG_TYPE}){
    $list = $Log->log_list({
      %LIST_PARAMS,
      COLS_NAME => 1,
      LOG_TYPE  => $FORM{LOG_TYPE},
      FROM_DATE => $FORM{DATE} || $FORM{FROM_DATE} || '',
      TO_DATE   => $FORM{DATE} || $FORM{TO_DATE} || ''
    });
  }


  my @header_arr = (
    "$lang{ALL}:index=$index",
    "AUTH:index=$index&ACTION=AUTH",
    "GUEST_MODE:index=$index&ACTION=GUEST_MODE",
    "HANGUP:index=$index&ACTION=HANGUP",
    "IPOE_LOGIN_NOT_EXIST:index=$index&TEXT=IPOE_LOGIN_NOT_EXIST",
    "USER_NOT_EXIST:index=$index&TEXT=USER_NOT_EXIST",
  );

  my $header = $html->table_header(\@header_arr, {
    SHOW_ONLY => 3
  });

  $table = $html->table({
    caption => "Internet $lang{ERROR}",
    width   => '100%',
    title   => [ $lang{DATE}, $lang{TYPE}, $lang{ACTION}, $lang{USER}, $lang{TEXT}, "NAS" ],
    pages   => $total,
    qs      => $pages_qs,
    header  => $header,
    ID      => 'INTERNET_ERRORS',
    EXPORT  => 1,
    MENU    => "$lang{SEARCH}:index=$index&search_form=1:search",
  });

  foreach my $line (@$list) {
    my $message = $line->{message};

    if($line->{log_type} < 5) {
      $message = $html->color_mark($line->{message}, $_COLORS[6]);
    }
    elsif($line->{action} eq 'GUEST_MODE') {
      $message = $html->color_mark($line->{message}, $_COLORS[8]);
      $line->{action} = $html->color_mark($line->{action}, $_COLORS[8]);
    }

    my $auth_switch = q{};

    #xx:xx:xx:xx:xx:xx xxxx.xxxx.xxxx
    if($message =~ /NAS_MAC: ([a-f\:0-9\.]{14,17})/i) {
      $auth_switch = $1;
      if($nas_ids{$auth_switch}) {
        $auth_switch = $nas_ids{$auth_switch};
      }
    }

    my $main_nas = ($line->{nas_id} && $nas_ids{ $line->{nas_id} }) ? $nas_ids{ $line->{nas_id} } : 'Unknown '. ($line->{nas_id} || q{});
    $table->addrow($line->{date},
      $log_levels_rev{ $line->{log_type} },
      $line->{action},
        ($conf{INTERNET_LOGIN}) ? $html->button($line->{user}, "index=". get_function_index('internet_users_list'). "&INTERNET_LOGIN=$line->{user}&search=1")  : $html->button($line->{user}, "index=11&LOGIN=$line->{user}"),
      $message,
        (! $auth_switch || $auth_switch eq $main_nas) ? $main_nas : $auth_switch . $html->br() . $main_nas
    );
  }

  print $table->show();

  #File part
  if (! $conf{LOGFILE} || !-f $conf{LOGFILE}) {
    $html->message('info', $lang{INFO}, "'". ($conf{LOGFILE} || q{}) . "' $lang{NOT_EXIST} (\$conf{LOGFILE})");
    return 0;
  }

  if (defined($FORM{LOG_TYPE})) {
    $pages_qs .= "&LOG_TYPE=$FORM{LOG_TYPE}";
  }

  my ($log_list, $types, $totals) = show_log(
    ($LIST_PARAMS{LOGIN} || ''),
    $conf{LOGFILE},
    {
      DATE      => $FORM{DATE},
      LOG_TYPE  => ($FORM{LOG_TYPE}) ? $log_levels_rev{ $FORM{LOG_TYPE} } : undef,
      PG        => $PG || 25,
      PAGE_ROWS => 25
    }
  );

  $table = $html->table(
    {
      caption => "System $lang{ERROR}",
      width   => '100%',
      pages   => $totals,
      qs      => $pages_qs,
      ID      => 'INTERNET_ERRORS2',
    }
  );

  foreach my $line (@$log_list) {
    if ($line =~ m/LOG_WARNING/i) {
      $line = $html->color_mark($line, $_COLORS[6]);
    }

    $table->addrow($line);
  }
  print $table->show();

  $table = $html->table(
    {
      width      => '100%',
    }
  );

  $table->addrow($html->button("$lang{TOTAL}", "index=$index&$pages_qs"), $totals);
  while (my ($k, $v) = each %$types) {
    $table->addrow($html->button($k, "index=$index&LOG_TYPE=$k$pages_qs"), $v);
  }

  $table->addrow($lang{SIZE}, int2byte((-s $conf{LOGFILE}))) if (! $LIST_PARAMS{LOGIN} || $LIST_PARAMS{LOGIN} eq '');

  print $table->show();

  return 1;
}

#**********************************************************
=head2 internet_payments_maked($attr) - Cross module payment maked

  Arguments:
    $attr
      USER_INFO
      SUM

=cut
#**********************************************************
sub internet_payments_maked {
  my ($attr) = @_;

  $user=$attr->{USER_INFO} if ($attr->{USER_INFO});
  return '' if ($FORM{DISABLE});

  my $service_list = $Internet->list({
    UID         => $user->{UID},
    TP_NUM      => '>0',
    GROUP_BY    => 'internet.id',
    COLS_NAME   => 1
  });

  foreach my $service (@$service_list) {
    $Internet->info($user->{UID}, { ID => $service->{id} });

    if ($Internet->{PERSONAL_TP} && $Internet->{PERSONAL_TP} > 0) {
      $Internet->{MONTH_ABON} = $Internet->{PERSONAL_TP};
    }

    my $deposit = (defined($user->{DEPOSIT})) ? $user->{DEPOSIT} + (($user->{CREDIT} > 0) ? $user->{CREDIT} : $Internet->{TP_CREDIT}) : 0;

    my $abon_fees = ($user->{REDUCTION} == 0) ? $Internet->{MONTH_ABON} + $Internet->{DAY_ABON} : ($Internet->{MONTH_ABON} + $Internet->{DAY_ABON}) * (100 - $user->{REDUCTION}) / 100;

    if ($conf{INTERNET_FULL_MONTH}) {
      $abon_fees = ($user->{REDUCTION} == 0) ? $Internet->{MONTH_ABON} + $Internet->{DAY_ABON} * 30 : ($Internet->{MONTH_ABON} + $Internet->{DAY_ABON} * 30) * (100 - $user->{REDUCTION}) / 100;
    }
    elsif ($Internet->{ABON_DISTRIBUTION}) {
      my $days_in_month = days_in_month({ DATE => $DATE });
      $abon_fees = ($Internet->{MONTH_ABON} / $days_in_month) + $Internet->{DAY_ABON};
    }

    #OLd method. Always change activate period with payments
    #@deprecated
    if ($conf{payment_chg_activate} && $Internet->{SERVICE_ACTIVATE} ne '0000-00-00') {
      if ($conf{payment_chg_activate} ne 2
        || date_diff($Internet->{SERVICE_ACTIVATE}, $DATE) > 30) {
        $Internet->change({
          ACTIVATE => $DATE,
          UID      => $user->{UID},
          ID       => $Internet->{ID},
        });
      }
    }

    if($user->{REDUCTION} && $user->{REDUCTION} > 0) {
      $abon_fees = $abon_fees * (100 - $user->{REDUCTION}) / 100;
    }

    if (in_array($Internet->{STATUS}, [4,5]) && $deposit > $abon_fees) {
      my %params = ();
      if ($conf{INTERNET_CUSTOM_PERIOD}) {
        if ($deposit >= $Internet->{TP_CHANGE_PRICE}) {
          if ($Internet->{TP_AGE}) {
            my ($y, $m, $d) = split(/-/, $DATE);
            $params{SERVICE_EXPIRE} = POSIX::strftime("%Y-%m-%d",
              localtime(POSIX::mktime(0, 0, 0, $d, ($m - 1), ($y - 1900), 0, 0, 0) + $Internet->{TP_AGE} * 86400));

            my $Fees = Fees->new($db, $admin, \%conf);
            $Fees->take($user, $Internet->{TP_CHANGE_PRICE}, { DESCRIBE => $lang{ACTIVATE_TARIF_PLAN} });
            $service->{DESCRIBE} = ($Internet->{TP_NAME} || "") . " $lang{SUM}: $Internet->{TP_CHANGE_PRICE}";
            $html->message('info', "$lang{ACTIVATE} $lang{INTERNET}", $service->{DESCRIBE});
          }
        }
        else {
          return 1;
        }
      }

      $Internet->change({
        UID    => $user->{UID},
        ID     => $Internet->{ID},
        STATUS => 0,
        %params
      });

      if ($conf{INTERNET_FULL_MONTH} && $Internet->{OLD_STATUS} && $Internet->{OLD_STATUS} == 5) {
        $attr->{FULL_MONTH_FEE} = 1;
      }

      #$Internet->{ACCOUNT_ACTIVATE} = $user->{ACTIVATE} || '0000-00-00';
      service_get_month_fee($Internet, $attr);
    }
    elsif ($conf{INTERNET_PAY_ACTIVATE}) {
      my $sum = $attr->{SUM} || 0;
      if ($Internet->{SERVICE_ACTIVATE} ne '0000-00-00' && date_diff($Internet->{SERVICE_ACTIVATE}, $DATE) > 30
        && $deposit - $sum <= 0 && $deposit > $abon_fees) {
        #&& $deposit - $sum <= 0 && $deposit > 0) {

        my %service_params = (
          UID              => $user->{UID},
          ID               => $Internet->{ID},
          STATUS           => 0,
          SERVICE_ACTIVATE => $DATE
        );

        if ($Internet->{STATUS}) {
          $service_params{STATUS} = 0;
        }

        $Internet->change(\%service_params);
      }
      service_get_month_fee($Internet, $attr);
    }
  }

  return 1;
}

#**********************************************************
=head2 internet_period_select($attr) - period select

  Arguments:
    $attr
      ID
      UID

=cut
#**********************************************************
sub internet_period_select {
  my ($attr) = @_;

  my $date_picker = $html->form_daterangepicker({
    NAME      => 'FROM_DATE/TO_DATE',
    FORM_NAME => 'report_panel',
    VALUE     => $attr->{DATE} || $FORM{'FROM_DATE_TO_DATE'},
    OUTPUT2RETURN => 1
  });

  my $dimension = $html->form_select('DIMENSION', {
    SELECTED => $FORM{DIMENSION},
    SEL_HASH => {
      ''   => 'Auto',
      'Kb' => 'Kb',
      'Mb' => 'Mb',
      'Gb' => 'Gb'
    },
    NO_ID => 1
  });

  return $html->tpl_show(_include('internet_user_portal_stats', 'Internet'), {
    DATE_PICKER => $date_picker,
    DIMENSION   => $dimension,
    ONLINE      => (! $FORM{rows} && ! $FORM{ONLINE}) ? '' : 'checked',
    ROWS        => ($conf{list_max_recs} && $conf{list_max_recs} =~ /^\d+$/) ? ($FORM{ROWS} || $conf{list_max_recs}) : 25,
    SID         => $sid,
    INDEX       => $index,
    ID          => $attr->{ID},
    UID         => $attr->{UID}
  }, { OUTPUT2RETURN => 1 });
}

#**********************************************************
=head2 internet_registration($attr)

  Arguments:
    $attr
      CAPTCHA
      CAPTCHA_OBJ
      SHOW_SMS
      QUITE


=cut
#**********************************************************
sub internet_registration {
  my ($attr) = @_;

  if ($FORM{reg}) {
#    if ($attr->{CAPTCHA} && $attr->{CAPTCHA_OBJ}->check_code($FORM{CCODE}, $FORM{C}) != 1) {
#      $Internet->{MESSAGE} = $html->message('err', $lang{ERROR}, "$lang{ERR_WRONG_CAPTCHA}", { ID => 991 });
#    }
#    els
    if ($attr->{SKIP_EMAIL_CHECK} && $FORM{EMAIL} !~ /^(([^<>()[\]\\.,;:\s\@\"]+(\.[^<>()[\]\\.,;:\s\@\"]+)*)|(\".+\"))\@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/) {
      $Internet->{MESSAGE} = $html->message('err', $lang{ERROR}, "$lang{ERR_WRONG_EMAIL}");
    }
    elsif ($conf{REGISTRATION_CHECK_PHONE}
      && (!$FORM{PHONE} || ($conf{PHONE_FORMAT} && $FORM{PHONE} !~ /$conf{PHONE_FORMAT}/ )) ) {
      $Internet->{MESSAGE} = $html->message('err', $lang{ERROR}, $lang{ERR_WRONG_PHONE}. (($conf{PHONE_FORMAT}) ? ' '.human_exp($conf{PHONE_FORMAT}) : q{}));
    }
    elsif (! $FORM{ACCEPT_RULES}) {
      $html->message('err', $lang{ERROR}, $lang{ERR_ACCEPT_RULES});
    }
    else {
      my $password = mk_unique_value($conf{PASSWD_LENGTH} || 8);

      $users->add(
        {
          LOGIN       => $FORM{LOGIN},
          CREATE_BILL => 1,
          PASSWORD    => $password,
          GID         => $conf{REGISTRATION_GID},
          PREFIX      => $conf{REGISTRATION_PREFIX},
        }
      );

      #my $message = '';
      if (!$users->{errno}) {
        my $uid = $users->{UID};
        $users->info($uid);

        if($FORM{AUTO_ADDRESS}){
          my $Address = Address->new($db, $admin, \%conf);
          my $district_id;
          my $street_id;
          my $location_id;

          my $districts = $Address->district_list({
            NAME         => "*$FORM{AUTO_DISTRICT}*",
            COLS_NAME    => 1
          });

          if($Address->{TOTAL} <= 0){
            $Address->district_add({
              NAME => $FORM{AUTO_DISTRICT},
              ZIP  => $FORM{AUTO_POST_CODE}
            });
            $district_id = $Address->{INSERT_ID};
          } else {
            $district_id = $districts->[0]->{id};
          }

          my $streets = $Address->street_list({
            STREET_NAME  => "*$FORM{AUTO_STREET}*",
            DISTRICT_ID  => $district_id,
            COLS_NAME    => 1
          });

          if($Address->{TOTAL} <= 0){
            $Address->street_add({
              NAME => $FORM{AUTO_STREET},
              DISTRICT_ID  => $district_id,
            });
            $street_id = $Address->{INSERT_ID};
          } else {
            $street_id = $streets->[0]->{id};
          }

          my $builds = $Address->build_list({
            STREET_ID   => $street_id,
            NUMBER      => "*$FORM{AUTO_BUILD}*",
            COLS_NAME    => 1
          });

          if($Address->{TOTAL} <= 0){
            $Address->build_add({
              NUMBER => $FORM{AUTO_BUILD},
              STREET_ID  => $street_id,
            });
            $location_id = $Address->{INSERT_ID};
          } else {
            $location_id = $builds->[0]->{id};
          }

          $FORM{LOCATION_ID} = $location_id;

        }

        #3 personal info
        $users->pi_add(
          {
            %FORM,
            UID   => $uid,
            FIO   => $FORM{FIO},
            EMAIL => $FORM{EMAIL}
          }
        );

        if ($users->{errno}) {
          $Internet->{MESSAGE} = $html->message('err', $lang{ERROR}, "[$users->{errno}] $err_strs{$users->{errno}}");
          goto REG_FORM;
        }

        #4 Dv
        $conf{REGISTRATION_DEFAULT_TP} = 0 if (!$conf{REGISTRATION_DEFAULT_TP});
        $Internet->add(
          {
            UID   => $uid,
            TP_ID => $FORM{TP_ID} || $conf{REGISTRATION_DEFAULT_TP},
            STATUS=> $FORM{STATUS}
          }
        );

        if (!$Internet->{errno}) {
          if ($conf{REGISTRATION_SHOW_PASSWD}) {
            $Internet->{PASSWD} = $password;
          }
          else {
            $Internet->{PASSWD} = "$lang{SEND_REG} E-mail";
          }

          $Internet->info($uid);
          if ($attr->{ACTIVATE_PAYMENT}) {
            $Payments->add(
              $users,
              {
                METHOD   => $attr->{PAYMENT_METHOD} || '2',
                SUM      => $Internet->{TP_ACTIVATE_PRICE},
              }
            );

            if ($FORM{STATUS}) {
              $Internet->change({
                UID    => $uid,
                STATUS => 0
              });

              service_get_month_fee($Internet, { QUITE => 1 });
            }
          }

          #show complete when user added
          if ($attr->{SHOW_SMS}) {
            $html->tpl_show(_include('internet_reg_complete_sms', 'Internet'), { %$Internet, %FORM, %{ ($users) ? $users : {} }, PASSWORD => "$password" });
          }
          elsif (! $attr->{QUITE}) {
            $html->tpl_show(_include('internet_reg_complete', 'Internet'), { %$Internet, %FORM, %{ ($users) ? $users : {} } });
          }

          #Sendsms
          if ($FORM{PHONE} && in_array('Sms', \@MODULES) && $conf{INTERNET_REGISTRATION_SEND_SMS} && ! $FORM{REGISTRATION_SKIP_SEND_SMS}) {
            load_module('Sms', $html);

            my $message = $html->tpl_show(_include('internet_reg_complete_sms', 'Internet'), { %FORM }, { OUTPUT2RETURN => 1  });;
            sms_send({
              NUMBER  => $FORM{PHONE},
              MESSAGE => $message,
              UID     => $uid,
            });
          }
          #Send mail
          if ($FORM{EMAIL}) {
            my $message = $html->tpl_show(_include('internet_reg_complete_mail', 'Internet'), { %$Internet, %FORM, PASSWORD => "$password" }, { OUTPUT2RETURN => 1 });
            sendmail($conf{ADMIN_MAIL}, $FORM{EMAIL}, $lang{REGISTRATION}, $message, $conf{MAIL_CHARSET}, '');
          }

          return $uid;
        }
        else {
          _error_show($Internet);
        }
      }
      else {
        _error_show($users);
        goto REG_FORM;
      }
    }
  }

  REG_FORM:

  if ($conf{INTERNET_REGISTRATION_TP_GIDS}) {
    $LIST_PARAMS{TP_GID} = $conf{INTERNET_REGISTRATION_TP_GIDS};
  }
  else {
    $LIST_PARAMS{TP_GID} = '>0';
  }

  $Internet->{TP_SEL} = $html->form_select(
    'TP_ID',
    {
      SELECTED => $FORM{TP_ID},
      SEL_LIST => $Tariffs->list({ %LIST_PARAMS,
        MODULE       => 'Dv;Internet',
        STATUS       => '<1',
        NEW_MODEL_TP => 1,
        COLS_NAME    => 1 }),
      SEL_KEY   => 'tp_id'
    }
  );

  if($conf{INTERNET_AUTO_REGISTRATION_ADDRESS}) {
    $attr->{API_KEY} = $conf{INTERNET_AUTO_REGISTRATION_ADDRESS};
    $attr->{REGION} = $conf{INTERNET_AUTO_REGISTRATION_ADDRESS_REGIONS};
    $attr->{LANG} = $conf{INTERNET_AUTO_REGISTRATION_ADDRESS_LANG};

    $Internet->{ADDRESS_TPL} = $html->tpl_show(_include('form_internet_auto_address', 'Internet'),
      { %$Internet, %$attr, %FORM }, {ID => 'INTERNET_AUTO_ADDRESS', OUTPUT2RETURN => 1});
  }
  elsif ($conf{INTERNET_REGISTRATION_ADDRESS}) {
    require Control::Address_mng;
    $Internet->{ADDRESS_TPL} = form_address_select2();
#      $html->tpl_show(templates('form_address_search'), { %FORM, %$attr },
#      { OUTPUT2RETURN => 1, ID => 'form_address_sel' });
  }

  $html->tpl_show(_include('internet_registration', 'Internet'), { %$Internet, %$attr, %FORM }, { ID => 'INTERNET_REGISTRATION' });

  return 0;
}

#**********************************************************
=head2 internet_docs($attr) - get services for invoice

  Arguments:
    UID
    FEES_INFO
    SKIP_DISABLED
    FULL_INFO

  Returns:


=cut
#**********************************************************
sub internet_docs {
  my ($attr) = @_;

  my $uid      = $attr->{UID} || $FORM{UID};
  my @services = ();
  my %info     = ();
  our %FEES_METHODS;

  my $service_list = $Internet->list({
    UID              => $uid,
    MONTH_FEE        => '_SHOW',
    DAY_FEE          => '_SHOW',
    PERSONAL_TP      => '_SHOW',
    INTERNET_STATUS  => '_SHOW',
    ABON_DISTRIBUTION=> '_SHOW',
    TP_NAME          => '_SHOW',
    FEES_METHOD      => '_SHOW',
    TP_ID            => '_SHOW',
    TP_NUM           => '_SHOW',
    TP_FIXED_FEES_DAY=> '_SHOW',
    INTERNET_ACTIVATE=> '_SHOW',
    INTERNET_EXPIRE  => '_SHOW',
    TP_REDUCTION_FEE => '_SHOW',
    GROUP_BY         => 'internet.id',
    COLS_NAME        => 1
  });

  if ($attr->{FEES_INFO} || $attr->{FULL_INFO}) {
    foreach my $service_info ( @{ $service_list } ) {
      my %FEES_DSC = (
        MODULE          => 'Internet',
        TP_ID           => $service_info->{tp_id},
        TP_NAME         => $service_info->{tp_name},
        FEES_PERIOD_DAY => $lang{MONTH_FEE_SHORT},
        FEES_METHOD     => $service_info->{fees_method} ? $FEES_METHODS{$service_info->{fees_method}} : undef,
      );

      $info{service_name}      = fees_dsc_former(\%FEES_DSC);
      $info{service_desc}      = q{};
      $info{tp_name}           = $service_info->{tp_name};
      $info{service_activate}  = $service_info->{internet_activate};
      $info{service_expire}    = $service_info->{internet_expire};
      $info{tp_fixed_fees_day} = $service_info->{tp_fixed_fees_day} || 0;
      $info{status}            = $service_info->{internet_status};
      $info{tp_reduction_fee}  = $service_info->{tp_reduction_fee};
      $info{module_name}       = $lang{INTERNET};

      if ($service_info->{internet_status} && $service_info->{internet_status} != 5 && $attr->{SKIP_DISABLED}) {
        $info{day} = 0;
        $info{month} = 0;
        $info{abon_distribution} = 0;
      }
      else {
        if ($service_info->{personal_tp} && $service_info->{personal_tp} > 0) {
          $info{day}   = $service_info->{day_fee};
          $info{month} = $service_info->{personal_tp};
          $info{abon_distribution} = $service_info->{abon_distribution};
        }
        else {
          $info{day} = $service_info->{day_fee};
          $info{month} = $service_info->{month_fee};
          $info{abon_distribution} = $service_info->{abon_distribution};
        }
      }

      return \%info if(! $attr->{FULL_INFO});

      push @services, { %info };
    }
  }

  if($attr->{FULL_INFO}) {
    return \@services;
  }

  if ($Internet->{TOTAL} < 1
#  if ($Internet->{TOTAL}==0 || ($Internet->{STATUS} && $Internet->{STATUS} != 5)
#    #|| ($attr->{PAYMENT_TYPE} && ($Internet->{POSTPAID_ABON} || $Internet->{PAYMENT_TYPE}))
  ) {
    return \@services;
  }

  foreach my $service_info ( @$service_list ) {
    if($service_info->{internet_status} && $service_info->{internet_status} != 5 && ! $attr->{SHOW_ALL}) {
      next
    }

    if($service_info->{personal_tp} && $service_info->{personal_tp} > 0) {
      $service_info->{month_fee} = $service_info->{personal_tp};
    }

    if ($service_info->{month_fee} && $service_info->{month_fee} > 0) {
      my %FEES_DSC = (
        MODULE          => 'Internet',
        TP_ID           => $service_info->{tp_id},
        TP_NAME         => $service_info->{tp_name},
        FEES_PERIOD_DAY => $lang{MONTH_FEE_SHORT},
        FEES_METHOD     => $service_info->{fees_method} ? $FEES_METHODS{$service_info->{fees_method}} : undef,
      );

      #Fixme / make hash export
      push @services, fees_dsc_former(\%FEES_DSC) . "||$service_info->{month_fee}|$service_info->{tp_num}|$service_info->{tp_name}"
        ."|$service_info->{fees_method}|$service_info->{internet_activate}|$service_info->{internet_status}";
    }

    if ($service_info->{day_fee} && $service_info->{day_fee} > 0) {
      my $days_in_month = days_in_month({ DATE => next_month({ DATE => $DATE }) });
      #Describe| days | sum
      push @services, "Internet: $lang{MONTH_FEE_SHORT}: $service_info->{tp_name} ($service_info->{tp_id})|$days_in_month $lang{DAY}|"
        . sprintf("%.2f", ($service_info->{day_fee} * $days_in_month)) . "||$service_info->{tp_name}"
        . "|$service_info->{fees_method}|$service_info->{internet_activate}";
    }
  }

  return \@services;
}


#**********************************************************
=head internet_quick_info($attr) - Quick information

  Arguments:
    $attr
      UID

  Return:

=cut
#**********************************************************
sub internet_quick_info {
  my ($attr) = @_;
  my $result;

  my $uid = $attr->{UID} || $FORM{UID};

  if ($attr->{UID}) {
    my $list = $Internet->list({
      UID        =>  $uid,
      TP_NAME    => '_SHOW',
      MONTH_FEE  => '_SHOW',
      CID        => '_SHOW',
      TP_COMMENTS=> '_SHOW',
      INTERNET_STATUS => '_SHOW',
      INTERNET_STATUS_ID => '_SHOW',
      IP         => '_SHOW',
      COLS_NAME  => 1,
      COLS_UPPER => 1
    });

    $result = $list->[0];
    my $service_status = sel_status({ HASH_RESULT => 1 });
    $result->{STATUS} = (defined($result->{INTERNET_STATUS})) ? $service_status->{ $result->{INTERNET_STATUS} } : '';
    ($result->{STATUS}, undef)=split(/:/, $result->{STATUS});
    return $result;
  }
  elsif($attr->{GET_PARAMS}) {
    $result = {
      HEADER    => $lang{INTERNET},
      QUICK_TPL => 'internet_qi_box',
      FIELDS => {
        TP_NAME     => $lang{TARIF_PLAN},
        CID         => 'CID',
        IP          => 'IP',
        STATUS      => $lang{STATUS},
        INTERNET_STATUS_ID => "$lang{STATUS} ID",
        MONTH_FEE   => $lang{MONTH_FEE},
        TP_COMMENTS => $lang{COMMENTS},
      }
    };

    return $result;
  }

  $Internet->list({
    UID       => $uid,
    LOGIN     => (! $uid && $attr->{LOGIN}) ? $attr->{LOGIN} : undef,
    COLS_NAME => 1,
  });

  return ($Internet->{TOTAL_SERVICES} && $Internet->{TOTAL_SERVICES} > 0) ? $Internet->{TOTAL_SERVICES} : '';
}


#**********************************************************
=head2 _sec2time_str($sec);

=cut
#**********************************************************
sub _sec2time_str {
  my($value) = @_;

  return sec2time($value, { str => 1 });
}


#**********************************************************
=head2 internet_search($attr) - Global search submodule

  Arguments:
    $attr
      SEARCH_TEXT
      DEBUG

  Returs:
     TRUE/FALSE

=cut
#**********************************************************
sub internet_search {
  my($attr) = @_;

  my @default_search = ('CID', 'CPE_MAC', 'INTERNET_LOGIN', '_MULTI_HIT');

  if($attr->{SEARCH_TEXT} =~ /^[0-9\.]+$/) {
    push @default_search, 'IP';
  }

  my @qs = ();
  foreach my $field ( @default_search ) {
    $LIST_PARAMS{$field} = "*$attr->{SEARCH_TEXT}*";
    push @qs, "$field=*$attr->{SEARCH_TEXT}*";
  }

  if($attr->{DEBUG}) {
    $Internet->{debug} = 1;
  }

  my $intertnet_list = $Internet->list({
    %LIST_PARAMS,
    UNIVERSAL_SEARCH => 1,
    COLS_NAME => 1
  });

  my $admin_permissions_gid = 0;
  if ($admin->{GID}) {
    my @admin_gids = split(/,/, $admin->{GID});

    my $user_gid = $users->info($intertnet_list->[0]->{uid});
    if ($#admin_gids > 0) {
      foreach my $admin_gid (@admin_gids) {
        if ($user_gid->{GID} && $admin_gid == $user_gid->{GID}) {
          $admin_permissions_gid = 1
        }
        elsif (!$user_gid->{GID}) {
          $admin_permissions_gid = 1
        }
      }
    }
    elsif ($#admin_gids < 1 && $admin->{GID}) {
      $admin_permissions_gid = 1;
    }
  }
  else {
    $admin_permissions_gid = 1;
  }

  my @info = ();

  if ($admin_permissions_gid) {
    if($Internet->{TOTAL}) {
      push @info, {
        'TOTAL'        => $Internet->{TOTAL},
        'MODULE'       => 'Internet',
        'MODULE_NAME'  => $lang{INTERNET},
        'SEARCH_INDEX' => get_function_index('internet_users_list')
          . '&' . join('&', @qs) . "&search=1&GLOBAL=1"
      };
    }
  }

  #Online
  my $Sessions = Internet::Sessions->new($db, $admin, \%conf);

  if ($permissions{5} && $permissions{5}{0}) {
    @default_search = ('CID', '_MULTI_HIT');

    if($attr->{SEARCH_TEXT} =~ /^[0-9\.]+$/) {
      push @default_search, 'IP';
    }

    @qs = ();
    foreach my $field ( @default_search ) {
      $LIST_PARAMS{$field} = "*$attr->{SEARCH_TEXT}*";
      push @qs, "$field=*$attr->{SEARCH_TEXT}*";
    }

    $Sessions->online({ %LIST_PARAMS, ALL => 1 });

    if($Sessions->{TOTAL}) {
      push @info, {
        'TOTAL'        => $Sessions->{TOTAL},
        'MODULE'       => 'Internet',
        'MODULE_NAME'  => "$lang{INTERNET} ONLINE",
        'SEARCH_INDEX' => get_function_index('internet_online')
          . '&' . join('&', @qs) . "&search=1"
      };
    }
  }

  #Stats
  if ($permissions{3} && $permissions{3}{6}) {
    $Sessions->list({ %LIST_PARAMS });

    if($Sessions->{TOTAL}) {
      push @info, {
          'TOTAL'        => $Sessions->{TOTAL},
          'MODULE'       => 'Internet',
          'MODULE_NAME'  => "$lang{INTERNET} $lang{STATS}",
          'SEARCH_INDEX' => get_function_index('internet_sessions')
            . '&' . join('&', @qs) . "&search=1"
        };
    }
  }

  return \@info;
}

#**********************************************************
=head internet_traffic_names($tp_id)

=cut
#**********************************************************
sub internet_traffic_names {
  my ($tp_id) = @_;

  my %TRAFFIC_NAMES = ();
  $Tariffs->ti_list({ TP_ID => $tp_id });
  if ($Tariffs->{TOTAL} > 0) {
    my $list = $Tariffs->tt_list({ TI_ID => $Tariffs->{list}->[0]->[0], COLS_NAME => 1 });
    foreach my $line (@$list) {
      $TRAFFIC_NAMES{ $line->{id} } = $line->{descr};
    }
  }

  return \%TRAFFIC_NAMES;
}


#**********************************************************
=head set_tags_users($ids, {$attr})

  Arguments:
    $ids    - Select users array sevice id
    $attr
      TAGS  - Tags array id

  Returns:
    -

=cut
#**********************************************************
sub set_tags_users {
  my ($ids, $attr) = @_;

  if (!$attr->{TAGS}) {
    $html->message('err', $lang{MULTIUSER_OP}, "$lang{SELECT_TAG}");

    return 1;
  }
  my $tags_users = $Internet->list({
    COLS_NAME => 1,
  });

  my %hash = map { $_ => $_ } split(', ', $ids);

  foreach my $user_ids (@$tags_users) {
    if ($hash{ $user_ids->{id} }) {
      tags_user_add({
        UID => $user_ids->{uid},
        IDS => $attr->{TAGS}
      });
    }
  }

  return 1;
}

1
