_{STORAGE_RESERVE_NOTIFY_USER}_: %LOGIN%
_{STORAGE_RESERVE_NOTIFY_ARTICLE}_: %ARTICLE_NAME%
_{STORAGE_RESERVE_NOTIFY_COUNT}_: %COUNT%
_{STORAGE_RESERVE_NOTIFY_PRICE}_: %SELL_PRICE%
_{STORAGE_RESERVE_NOTIFY_STORAGE}_: %STORAGE_NAME%

_{STORAGE_RESERVE_NOTIFY_ACTION}_
