<tr>
  <td><small>%date%</small></td>
  <td><small>%login%</small></td>
  <td><small>%fio%</small></td>
  <td><small>(%date%-%date%)</small></td>
  <td><small>%fees_sum%</small></td>
  <td><small>%payment_sum%</small></td>
  <td><small>%deposit%</small></td>
</tr>
