<!DOCTYPE html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Невідомий пристрій</title>
  <style>
    *, ::after, ::before {
      box-sizing: border-box;
    }
    body {
      background-color: #FDB10B;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";
      font-size: 1rem;
      font-weight: 400;
      line-height: 1.5;
      color: #FEF4C0;
      text-align: left;
      text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
    }
    a {
      color: #007bff;
      text-decoration: none;
      background-color: transparent;
    }
    .container {
      max-width: 600px;
      text-align: center;
    }
    .card {
      position: relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-direction: column;
      flex-direction: column;
      min-width: 0;
      word-wrap: break-word;
      background-clip: border-box;
      border: 1px solid rgba(0,0,0,.125);
      border-radius: .25rem;
    }
    .card {
      border: none;
      border-radius: 15px;
    }
    .card-body {
      -ms-flex: 1 1 auto;
      flex: 1 1 auto;
      min-height: 1px;
      padding: 1.25rem;
    }
    .card-body {
      padding: 2rem;
    }
    .btn {
      display: inline-block;
      font-weight: 400;
      color: #212529;
      text-align: center;
      vertical-align: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
      background-color: transparent;
      border: 1px solid transparent;
      padding: .375rem .75rem;
      font-size: 1rem;
      line-height: 1.5;
      border-radius: .25rem;
      transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
      font-size: 1.25rem;
      padding: 0.75rem 1.5rem;
      margin: 0.5rem;
    }
    .btn-primary {
      color: #fff;
      background-color: #007bff;
      border-color: #007bff;
    }
    .container {
      width: 100%;
      padding-right: 15px;
      padding-left: 15px;
      margin-right: auto;
      margin-left: auto;
     }
  </style>
</head>
<body>
<div class="container">
  <div class="card">
    <div class="card-body">
      <!-- You can put your inline svg logo here. -->
      <h2>
        Невідомий пристрій, зареєструйте його або зверніться в відділ підтримки
      </h2>
      <a href="https://YOUR.PORTAL:9443/" class="btn btn-primary">Зареєструвати пристрій</a>
    </div>
  </div>
</div>
</body>
</html>
